// Export all services from a single index file for easy imports
export { default as api } from './api'
export { default as authService } from './authService'
export { default as userService } from './userService'
export { default as patientService } from './patientService'
export { default as vaccineService } from './vaccineService'
export { default as inventoryService } from './inventoryService'
export { default as immunizationService } from './immunizationService'
export { default as smsService } from './smsService'
export { default as dashboardService } from './dashboardService'
export { default as reportService } from './reportService'