<template>
  <AdminLayout>
    <div class="container-fluid p-4">
      <AppPageHeader 
        title="Reports & Analytics" 
        subtitle="Generate and view comprehensive system reports"
      >
        <template #actions>
          <div class="d-flex gap-2">
            <button class="btn btn-outline-primary" @click="refreshReports">
              <i class="bi bi-arrow-clockwise me-2"></i>Refresh
            </button>
            <button class="btn btn-primary" @click="showGenerateModal = true">
              <i class="bi bi-plus-circle me-2"></i>Generate Report
            </button>
          </div>
        </template>
      </AppPageHeader>

      <!-- Report Filters -->
      <div class="card mb-4">
        <div class="card-body">
          <div class="row g-3">
            <div class="col-md-3">
              <label class="form-label">Date Range</label>
              <select class="form-select" v-model="selectedDateRange" @change="applyFilters">
                <option value="last_7_days">Last 7 Days</option>
                <option value="last_30_days">Last 30 Days</option>
                <option value="last_3_months">Last 3 Months</option>
                <option value="last_6_months">Last 6 Months</option>
                <option value="last_year">Last Year</option>
                <option value="custom">Custom Range</option>
              </select>
            </div>
            <div class="col-md-3">
              <label class="form-label">Report Type</label>
              <select class="form-select" v-model="selectedType" @change="applyFilters">
                <option value="">All Types</option>
                <option value="vaccination">Vaccination</option>
                <option value="inventory">Inventory</option>
                <option value="patient">Patient</option>
                <option value="analytics">Analytics</option>
              </select>
            </div>
            <div class="col-md-3">
              <label class="form-label">Status</label>
              <select class="form-select" v-model="selectedStatus" @change="applyFilters">
                <option value="">All Status</option>
                <option value="completed">Completed</option>
                <option value="generating">Generating</option>
                <option value="failed">Failed</option>
              </select>
            </div>
            <div class="col-md-3">
              <div class="d-flex align-items-end h-100">
                <button class="btn btn-outline-secondary w-100" @click="resetFilters">
                  <i class="bi bi-funnel"></i> Clear Filters
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <!-- Reports List -->
        <div class="col-lg-8">
          <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex justify-content-between align-items-center">
              <h6 class="m-0 fw-bold text-primary">Generated Reports</h6>
              <span class="badge bg-primary">{{ totalReports }} reports</span>
            </div>
            <div class="card-body">
              <!-- Loading State -->
              <div v-if="loading" class="text-center py-4">
                <div class="spinner-border text-primary" role="status">
                  <span class="visually-hidden">Loading reports...</span>
                </div>
              </div>

              <!-- Reports Table -->
              <div v-else-if="reports.length > 0" class="table-responsive">
                <table class="table table-hover">
                  <thead class="table-light">
                    <tr>
                      <th>Report Name</th>
                      <th>Type</th>
                      <th>Generated</th>
                      <th>Generated By</th>
                      <th>Status</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="report in reports" :key="report.id">
                      <td>
                        <div>
                          <span class="fw-semibold">{{ report.name }}</span>
                          <div class="text-muted small">{{ report.description }}</div>
                        </div>
                      </td>
                      <td>
                        <span class="badge" :class="getTypeBadgeClass(report.type)">
                          {{ report.type }}
                        </span>
                      </td>
                      <td>
                        <div>
                          {{ formatDate(report.createdAt) }}
                          <div class="text-muted small">{{ formatTime(report.createdAt) }}</div>
                        </div>
                      </td>
                      <td>{{ report.generatedBy }}</td>
                      <td>
                        <span class="badge" :class="getStatusBadgeClass(report.status)">
                          <i :class="getStatusIcon(report.status)" class="me-1"></i>
                          {{ report.status }}
                        </span>
                      </td>
                      <td>
                        <div class="btn-group btn-group-sm">
                          <button 
                            v-if="report.status === 'completed'" 
                            class="btn btn-outline-primary" 
                            @click="downloadReport(report)"
                            title="Download"
                          >
                            <i class="bi bi-download"></i>
                          </button>
                          <button 
                            class="btn btn-outline-info" 
                            @click="viewReport(report)"
                            title="View"
                          >
                            <i class="bi bi-eye"></i>
                          </button>
                          <button 
                            class="btn btn-outline-success" 
                            @click="shareReport(report)"
                            title="Share"
                          >
                            <i class="bi bi-share"></i>
                          </button>
                          <button 
                            class="btn btn-outline-danger" 
                            @click="deleteReport(report)"
                            title="Delete"
                          >
                            <i class="bi bi-trash"></i>
                          </button>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <!-- Empty State -->
              <div v-else class="text-center py-5">
                <i class="bi bi-file-text text-muted" style="font-size: 4rem;"></i>
                <h5 class="mt-3 text-muted">No reports found</h5>
                <p class="text-muted">Generate your first report to get started</p>
                <button class="btn btn-primary" @click="showGenerateModal = true">
                  <i class="bi bi-plus-circle me-2"></i>Generate Report
                </button>
              </div>
            </div>

            <!-- Pagination -->
            <div class="card-footer" v-if="totalPages > 1">
              <AppPagination
                :current-page="currentPage"
                :total-pages="totalPages"
                :total-items="totalReports"
                :items-per-page="itemsPerPage"
                @page-change="changePage"
              />
            </div>
          </div>
        </div>

        <!-- Report Templates & Analytics -->
        <div class="col-lg-4">
          <!-- Quick Actions -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 fw-bold text-primary">Quick Reports</h6>
            </div>
            <div class="card-body">
              <div class="d-grid gap-2">
                <button class="btn btn-outline-primary text-start" @click="generateQuickReport('vaccination_summary')">
                  <i class="bi bi-shield-check me-2"></i>Vaccination Summary
                </button>
                <button class="btn btn-outline-success text-start" @click="generateQuickReport('inventory_status')">
                  <i class="bi bi-boxes me-2"></i>Inventory Status
                </button>
                <button class="btn btn-outline-info text-start" @click="generateQuickReport('patient_stats')">
                  <i class="bi bi-people me-2"></i>Patient Statistics
                </button>
                <button class="btn btn-outline-warning text-start" @click="generateQuickReport('monthly_report')">
                  <i class="bi bi-calendar-month me-2"></i>Monthly Report
                </button>
                <button class="btn btn-outline-secondary text-start" @click="generateQuickReport('compliance_report')">
                  <i class="bi bi-clipboard-check me-2"></i>Compliance Report
                </button>
              </div>
            </div>
          </div>

          <!-- Recent Activity -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 fw-bold text-primary">Recent Activity</h6>
            </div>
            <div class="card-body">
              <div class="timeline" v-if="recentActivity.length > 0">
                <div v-for="activity in recentActivity" :key="activity.id" class="timeline-item mb-3">
                  <div class="d-flex">
                    <div class="timeline-marker me-3">
                      <i :class="activity.icon" class="text-primary"></i>
                    </div>
                    <div class="timeline-content">
                      <p class="mb-1 text-sm">{{ activity.description }}</p>
                      <small class="text-muted">{{ formatTimeAgo(activity.timestamp) }}</small>
                    </div>
                  </div>
                </div>
              </div>
              <div v-else class="text-center text-muted py-3">
                <i class="bi bi-clock-history"></i>
                <p class="mt-2 mb-0">No recent activity</p>
              </div>
            </div>
          </div>

          <!-- Report Statistics -->
          <div class="card shadow">
            <div class="card-header py-3">
              <h6 class="m-0 fw-bold text-primary">Report Statistics</h6>
            </div>
            <div class="card-body">
              <div class="row text-center">
                <div class="col-6">
                  <div class="border-end">
                    <h4 class="text-primary mb-1">{{ reportStats.totalGenerated }}</h4>
                    <small class="text-muted">Total Reports</small>
                  </div>
                </div>
                <div class="col-6">
                  <h4 class="text-success mb-1">{{ reportStats.thisMonth }}</h4>
                  <small class="text-muted">This Month</small>
                </div>
              </div>
              <hr>
              <div class="row text-center">
                <div class="col-6">
                  <div class="border-end">
                    <h5 class="text-info mb-1">{{ reportStats.avgGenerationTime }}</h5>
                    <small class="text-muted">Avg Time</small>
                  </div>
                </div>
                <div class="col-6">
                  <h5 class="text-warning mb-1">{{ reportStats.mostUsedType }}</h5>
                  <small class="text-muted">Popular Type</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Generate Report Modal -->
      <div class="modal fade" :class="{ show: showGenerateModal }" :style="{ display: showGenerateModal ? 'block' : 'none' }" tabindex="-1">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Generate New Report</h5>
              <button type="button" class="btn-close" @click="closeGenerateModal"></button>
            </div>
            <div class="modal-body">
              <form @submit.prevent="generateReport">
                <div class="row g-3">
                  <div class="col-md-6">
                    <label class="form-label">Report Type *</label>
                    <select class="form-select" v-model="generateForm.type" required>
                      <option value="">Select Type</option>
                      <option value="vaccination">Vaccination Report</option>
                      <option value="inventory">Inventory Report</option>
                      <option value="patient">Patient Report</option>
                      <option value="analytics">Analytics Report</option>
                    </select>
                  </div>
                  <div class="col-md-6">
                    <label class="form-label">Report Name *</label>
                    <input type="text" class="form-control" v-model="generateForm.name" required>
                  </div>
                  <div class="col-12">
                    <label class="form-label">Description</label>
                    <textarea class="form-control" rows="3" v-model="generateForm.description"></textarea>
                  </div>
                  <div class="col-md-6">
                    <label class="form-label">Start Date</label>
                    <input type="date" class="form-control" v-model="generateForm.startDate">
                  </div>
                  <div class="col-md-6">
                    <label class="form-label">End Date</label>
                    <input type="date" class="form-control" v-model="generateForm.endDate">
                  </div>
                  <div class="col-12">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" v-model="generateForm.includeCharts" id="includeCharts">
                      <label class="form-check-label" for="includeCharts">
                        Include charts and visualizations
                      </label>
                    </div>
                  </div>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" @click="closeGenerateModal">Cancel</button>
              <button type="button" class="btn btn-primary" @click="generateReport" :disabled="generating">
                <span v-if="generating" class="spinner-border spinner-border-sm me-2"></span>
                Generate Report
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Modal Backdrop -->
      <div v-if="showGenerateModal" class="modal-backdrop fade show"></div>
    </div>
  </AdminLayout>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useToast } from '@/composables/useToast'
import AdminLayout from '@/components/layout/AdminLayout.vue'
import AppPageHeader from '@/components/common/AppPageHeader.vue'
import AppPagination from '@/components/common/AppPagination.vue'
import api from '@/services/api'

// Reactive data
const loading = ref(true)
const generating = ref(false)
const reports = ref([])
const selectedDateRange = ref('last_30_days')
const selectedType = ref('')
const selectedStatus = ref('')
const currentPage = ref(1)
const itemsPerPage = ref(10)
const totalReports = ref(0)
const totalPages = ref(0)

// Modal states
const showGenerateModal = ref(false)

// Form data
const generateForm = ref({
  type: '',
  name: '',
  description: '',
  startDate: '',
  endDate: '',
  includeCharts: true
})

// Activity and stats
const recentActivity = ref([])
const reportStats = ref({
  totalGenerated: 0,
  thisMonth: 0,
  avgGenerationTime: '2.5s',
  mostUsedType: 'Vaccination'
})

// Methods
const fetchReports = async () => {
  try {
    loading.value = true
    const params = {
      page: currentPage.value,
      limit: itemsPerPage.value
    }
    
    if (selectedType.value) params.type = selectedType.value
    if (selectedStatus.value) params.status = selectedStatus.value
    if (selectedDateRange.value !== 'custom') params.dateRange = selectedDateRange.value

    // For now, using mock data since we don't have a reports endpoint yet
    const mockReports = [
      {
        id: 1,
        name: 'Monthly Vaccination Summary - August 2025',
        description: 'Comprehensive vaccination data for August 2025',
        type: 'vaccination',
        status: 'completed',
        createdAt: '2025-08-15T10:30:00Z',
        generatedBy: 'Admin User',
        fileSize: '2.4 MB',
        downloadCount: 5
      },
      {
        id: 2,
        name: 'Inventory Status Report',
        description: 'Current vaccine inventory levels and alerts',
        type: 'inventory',
        status: 'completed',
        createdAt: '2025-08-14T14:20:00Z',
        generatedBy: 'System Admin',
        fileSize: '1.8 MB',
        downloadCount: 3
      },
      {
        id: 3,
        name: 'Patient Demographics Analysis',
        description: 'Statistical analysis of patient demographics',
        type: 'analytics',
        status: 'generating',
        createdAt: '2025-08-14T16:45:00Z',
        generatedBy: 'Health Worker',
        fileSize: null,
        downloadCount: 0
      }
    ]

    const mockActivity = [
      {
        id: 1,
        description: 'Monthly report generated successfully',
        icon: 'bi bi-file-text',
        timestamp: '2025-08-15T10:30:00Z'
      },
      {
        id: 2,
        description: 'Inventory report downloaded by Admin',
        icon: 'bi bi-download',
        timestamp: '2025-08-14T15:20:00Z'
      }
    ]

    reports.value = mockReports
    recentActivity.value = mockActivity
    totalReports.value = mockReports.length
    totalPages.value = Math.ceil(totalReports.value / itemsPerPage.value)
    
    reportStats.value = {
      totalGenerated: 28,
      thisMonth: 8,
      avgGenerationTime: '2.5s',
      mostUsedType: 'Vaccination'
    }

  } catch (error) {
    console.error('Error fetching reports:', error)
    reports.value = []
    totalReports.value = 0
    totalPages.value = 0
  } finally {
    loading.value = false
  }
}

const generateQuickReport = async (type) => {
  const reportNames = {
    vaccination_summary: 'Vaccination Summary Report',
    inventory_status: 'Inventory Status Report',
    patient_stats: 'Patient Statistics Report',
    monthly_report: 'Monthly Activity Report',
    compliance_report: 'Compliance Report'
  }

  generateForm.value = {
    type: type.split('_')[0],
    name: reportNames[type],
    description: `Auto-generated ${reportNames[type].toLowerCase()}`,
    startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    endDate: new Date().toISOString().split('T')[0],
    includeCharts: true
  }

  await generateReport()
}

const generateReport = async () => {
  try {
    generating.value = true
    
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 2000))
    
    // Add new report to the list
    const newReport = {
      id: Date.now(),
      ...generateForm.value,
      status: 'completed',
      createdAt: new Date().toISOString(),
      generatedBy: 'Current User',
      fileSize: '1.2 MB',
      downloadCount: 0
    }
    
    reports.value.unshift(newReport)
    totalReports.value++
    
    closeGenerateModal()
    
  } catch (error) {
    console.error('Error generating report:', error)
    const { addToast } = useToast()
    addToast({ title: 'Error', message: 'Error generating report', type: 'error' })
  } finally {
    generating.value = false
  }
}

const changePage = (page) => {
  currentPage.value = page
  fetchReports()
}

const applyFilters = () => {
  currentPage.value = 1
  fetchReports()
}

const resetFilters = () => {
  selectedDateRange.value = 'last_30_days'
  selectedType.value = ''
  selectedStatus.value = ''
  currentPage.value = 1
  fetchReports()
}

const refreshReports = () => {
  fetchReports()
}

const closeGenerateModal = () => {
  showGenerateModal.value = false
  generateForm.value = {
    type: '',
    name: '',
    description: '',
    startDate: '',
    endDate: '',
    includeCharts: true
  }
}

const downloadReport = (report) => {
  console.log('Downloading report:', report.name)
  // Implement download functionality
}

const viewReport = (report) => {
  console.log('Viewing report:', report.name)
  // Implement view functionality
}

const shareReport = (report) => {
  console.log('Sharing report:', report.name)
  // Implement share functionality
}

const deleteReport = async (report) => {
  if (confirm(`Are you sure you want to delete "${report.name}"?`)) {
    reports.value = reports.value.filter(r => r.id !== report.id)
    totalReports.value--
  }
}

// Utility functions
const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}

const formatTime = (dateString) => {
  return new Date(dateString).toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit'
  })
}

const formatTimeAgo = (dateString) => {
  const now = new Date()
  const date = new Date(dateString)
  const diffInHours = Math.floor((now - date) / (1000 * 60 * 60))
  
  if (diffInHours < 1) return 'Just now'
  if (diffInHours < 24) return `${diffInHours}h ago`
  const diffInDays = Math.floor(diffInHours / 24)
  return `${diffInDays}d ago`
}

const getTypeBadgeClass = (type) => {
  const classes = {
    vaccination: 'bg-primary',
    inventory: 'bg-success',
    patient: 'bg-info',
    analytics: 'bg-warning text-dark'
  }
  return classes[type] || 'bg-secondary'
}

const getStatusBadgeClass = (status) => {
  const classes = {
    completed: 'bg-success',
    generating: 'bg-primary',
    failed: 'bg-danger'
  }
  return classes[status] || 'bg-secondary'
}

const getStatusIcon = (status) => {
  const icons = {
    completed: 'bi bi-check-circle',
    generating: 'bi bi-arrow-repeat',
    failed: 'bi bi-exclamation-triangle'
  }
  return icons[status] || 'bi bi-info-circle'
}

// Lifecycle
onMounted(() => {
  fetchReports()
})
</script>

<style scoped>
.timeline-marker {
  width: 24px;
  height: 24px;
  border-radius: 50%;
  background: #f8f9fa;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 2px solid #dee2e6;
}

.modal.show {
  background-color: rgba(0, 0, 0, 0.5);
}

.btn-group .btn {
  border-radius: 0.25rem;
  margin-right: 0.125rem;
}

.btn-group .btn:last-child {
  margin-right: 0;
}

.text-sm {
  font-size: 0.875rem;
}
</style>
