-- Alternative: Repopulate guardians based on existing users
-- This version creates guardians for all users with role 'guardian' or creates sample guardians

-- Method 1: Create guardians for existing users with role 'guardian'
-- Uncomment and modify as needed:

-- INSERT INTO guardians (
--     surname, firstname, middlename, birthdate, address, occupation,
--     contact_number, alternative_contact_number, email, family_number,
--     date_registered, user_id, is_deleted, created_at, created_by, updated_at, updated_by
-- )
-- SELECT
--     u.surname, u.firstname, u.middlename,
--     u.birthdate,
--     COALESCE(u.address, 'Address not specified'),
--     'Not specified', -- occupation
--     u.contact_number,
--     NULL, -- alternative_contact_number
--     u.email,
--     CONCAT('FAM-', LPAD(u.user_id::text, 3, '0')), -- family_number
--     CURRENT_TIMESTAMP, -- date_registered
--     u.user_id,
--     false, -- is_deleted
--     CURRENT_TIMESTAMP, -- created_at
--     1, -- created_by (admin user)
--     CURRENT_TIMESTAMP, -- updated_at
--     1  -- updated_by (admin user)
-- FROM users u
-- WHERE u.role = 'guardian'
-- AND NOT EXISTS (SELECT 1 FROM guardians g WHERE g.user_id = u.user_id);

-- Method 2: If you want to create guardians for ALL users (not just role 'guardian')
-- Uncomment and modify as needed:

-- INSERT INTO guardians (
--     surname, firstname, middlename, birthdate, address, occupation,
--     contact_number, alternative_contact_number, email, family_number,
--     date_registered, user_id, is_deleted, created_at, created_by, updated_at, updated_by
-- )
-- SELECT
--     u.surname, u.firstname, u.middlename,
--     u.birthdate,
--     COALESCE(u.address, 'Address not specified'),
--     CASE
--         WHEN u.role = 'health_worker' THEN 'Health Worker'
--         ELSE 'Guardian'
--     END, -- occupation
--     u.contact_number,
--     NULL, -- alternative_contact_number
--     u.email,
--     CONCAT('FAM-', LPAD(u.user_id::text, 3, '0')), -- family_number
--     CURRENT_TIMESTAMP, -- date_registered
--     u.user_id,
--     false, -- is_deleted
--     CURRENT_TIMESTAMP, -- created_at
--     1, -- created_by (admin user)
--     CURRENT_TIMESTAMP, -- updated_at
--     1  -- updated_by (admin user)
-- FROM users u
-- WHERE NOT EXISTS (SELECT 1 FROM guardians g WHERE g.user_id = u.user_id);

-- Method 3: Quick check - see what users exist and their roles
-- SELECT user_id, role, firstname, surname, contact_number FROM users ORDER BY user_id;

-- Method 4: If you need to manually adjust user_id values in the sample data
-- Check what user_ids actually exist:
-- SELECT user_id FROM users ORDER BY user_id;