<template>
  <AdminLayout>
    <div class="container-fluid">
      <AppPageHeader 
        title="Reports & Analytics" 
        subtitle="Generate and view comprehensive system reports"
      >
        <template #actions>
          <div class="d-flex gap-2">
            <button class="btn btn-outline-primary" @click="refreshReports">
              <i class="bi bi-arrow-clockwise me-2"></i>Refresh
            </button>
            <button v-if="activeTab === 'generated'" class="btn btn-primary" @click="showGenerateModal = true">
              <i class="bi bi-plus-circle me-2"></i>Generate Report
            </button>
            <button v-if="activeTab === 'receiving'" class="btn btn-primary" @click="goToCreateReceiving">
              <i class="bi bi-plus-circle me-2"></i>New Receiving Report
            </button>
          </div>
        </template>
      </AppPageHeader>

      <!-- Tabs Navigation -->
      <ul class="nav nav-tabs mb-4">
        <li class="nav-item">
          <a 
            class="nav-link" 
            :class="{ active: activeTab === 'generated' }"
            @click="activeTab = 'generated'"
            style="cursor: pointer;"
          >
            <i class="bi bi-file-earmark-text me-2"></i>Generated Reports
          </a>
        </li>
        <li class="nav-item">
          <a 
            class="nav-link" 
            :class="{ active: activeTab === 'receiving' }"
            @click="activeTab = 'receiving'"
            style="cursor: pointer;"
          >
            <i class="bi bi-receipt me-2"></i>Receiving Reports
          </a>
        </li>
      </ul>

      <!-- Generated Reports Tab Content -->
      <div v-if="activeTab === 'generated'">
      <!-- Report Filters -->
      <div class="card mb-4">
        <div class="card-body">
          <div class="row g-3">
            <div class="col-md-3">
              <label class="form-label">Date Range</label>
              <select class="form-select" v-model="selectedDateRange" @change="applyFilters">
                <option value="last_7_days">Last 7 Days</option>
                <option value="last_30_days">Last 30 Days</option>
                <option value="last_3_months">Last 3 Months</option>
                <option value="last_6_months">Last 6 Months</option>
                <option value="last_year">Last Year</option>
                <option value="custom">Custom Range</option>
              </select>
            </div>
            <div class="col-md-3">
              <label class="form-label">Report Type</label>
              <select class="form-select" v-model="selectedType" @change="applyFilters">
                <option value="">All Types</option>
                <option value="vaccination">Vaccination</option>
                <option value="inventory">Inventory</option>
                <option value="patient">Patient</option>
                <option value="analytics">Analytics</option>
              </select>
            </div>
            <div class="col-md-3">
              <label class="form-label">Status</label>
              <select class="form-select" v-model="selectedStatus" @change="applyFilters">
                <option value="">All Status</option>
                <option value="completed">Completed</option>
                <option value="generating">Generating</option>
                <option value="failed">Failed</option>
              </select>
            </div>
            <div class="col-md-3">
              <div class="d-flex align-items-end h-100">
                <button class="btn btn-outline-secondary w-100" @click="resetFilters">
                  <i class="bi bi-funnel"></i> Clear Filters
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <!-- Reports List -->
        <div class="col-lg-8">
          <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex justify-content-between align-items-center">
              <h6 class="m-0 fw-bold text-primary">Generated Reports</h6>
              <span class="badge bg-primary">{{ totalReports }} reports</span>
            </div>
            <div class="card-body">
              <!-- Loading State -->
              <div v-if="loading" class="text-center py-4">
                <div class="spinner-border text-primary" role="status">
                  <span class="visually-hidden">Loading reports...</span>
                </div>
              </div>

              <!-- Reports Table -->
              <div v-else-if="reports.length > 0" class="table-responsive">
                <table class="table table-hover">
                  <thead class="table-light">
                    <tr>
                      <th>Report Name</th>
                      <th>Type</th>
                      <th>Generated</th>
                      <th>Generated By</th>
                      <th>Status</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="report in reports" :key="report.id">
                      <td>
                        <div>
                          <span class="fw-semibold">{{ report.name }}</span>
                          <div class="text-muted small">{{ report.description }}</div>
                        </div>
                      </td>
                      <td>
                        <span class="badge" :class="getTypeBadgeClass(report.type)">
                          {{ report.type }}
                        </span>
                      </td>
                      <td>
                        <div>
                          {{ formatDate(report.createdAt) }}
                          <div class="text-muted small">{{ formatTime(report.createdAt) }}</div>
                        </div>
                      </td>
                      <td>{{ report.generatedBy }}</td>
                      <td>
                        <span class="badge" :class="getStatusBadgeClass(report.status)">
                          <i :class="getStatusIcon(report.status)" class="me-1"></i>
                          {{ report.status }}
                        </span>
                      </td>
                      <td>
                        <div class="btn-group btn-group-sm">
                          <button 
                            v-if="report.status === 'completed'" 
                            class="btn btn-outline-primary" 
                            @click="downloadReport(report)"
                            title="Download"
                          >
                            <i class="bi bi-download"></i>
                          </button>
                          <button 
                            class="btn btn-outline-info" 
                            @click="viewReport(report)"
                            title="View"
                          >
                            <i class="bi bi-eye"></i>
                          </button>
                          <button 
                            class="btn btn-outline-success" 
                            @click="shareReport(report)"
                            title="Share"
                          >
                            <i class="bi bi-share"></i>
                          </button>
                          <button 
                            class="btn btn-outline-danger" 
                            @click="deleteReport(report)"
                            title="Delete"
                          >
                            <i class="bi bi-trash"></i>
                          </button>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <!-- Empty State -->
              <div v-else class="text-center py-5">
                <i class="bi bi-file-text text-muted" style="font-size: 4rem;"></i>
                <h5 class="mt-3 text-muted">No reports found</h5>
                <p class="text-muted">Generate your first report to get started</p>
                <button class="btn btn-primary" @click="showGenerateModal = true">
                  <i class="bi bi-plus-circle me-2"></i>Generate Report
                </button>
              </div>
            </div>

            <!-- Pagination -->
            <div class="card-footer" v-if="totalPages > 1">
              <AppPagination
                :current-page="currentPage"
                :total-pages="totalPages"
                :total-items="totalReports"
                :items-per-page="itemsPerPage"
                @page-change="changePage"
              />
            </div>
          </div>
        </div>

        <!-- Report Templates & Analytics -->
        <div class="col-lg-4">
          <!-- Quick Actions -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 fw-bold text-primary">Quick Reports</h6>
            </div>
            <div class="card-body">
              <div class="d-grid gap-2">
                <button class="btn btn-outline-primary text-start" @click="generateQuickReport('vaccination_summary')">
                  <i class="bi bi-shield-check me-2"></i>Vaccination Summary
                </button>
                <button class="btn btn-outline-success text-start" @click="generateQuickReport('inventory_status')">
                  <i class="bi bi-boxes me-2"></i>Inventory Status
                </button>
                <button class="btn btn-outline-info text-start" @click="generateQuickReport('patient_stats')">
                  <i class="bi bi-people me-2"></i>Patient Statistics
                </button>
                <button class="btn btn-outline-warning text-start" @click="generateQuickReport('monthly_report')">
                  <i class="bi bi-calendar-month me-2"></i>Monthly Report
                </button>
                <button class="btn btn-outline-secondary text-start" @click="generateQuickReport('compliance_report')">
                  <i class="bi bi-clipboard-check me-2"></i>Compliance Report
                </button>
              </div>
            </div>
          </div>

          <!-- Recent Activity -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 fw-bold text-primary">Recent Activity</h6>
            </div>
            <div class="card-body">
              <div class="timeline" v-if="recentActivity.length > 0">
                <div v-for="activity in recentActivity" :key="activity.id" class="timeline-item mb-3">
                  <div class="d-flex">
                    <div class="timeline-marker me-3">
                      <i :class="activity.icon" class="text-primary"></i>
                    </div>
                    <div class="timeline-content">
                      <p class="mb-1 text-sm">{{ activity.description }}</p>
                      <small class="text-muted">{{ formatTimeAgo(activity.timestamp) }}</small>
                    </div>
                  </div>
                </div>
              </div>
              <div v-else class="text-center text-muted py-3">
                <i class="bi bi-clock-history"></i>
                <p class="mt-2 mb-0">No recent activity</p>
              </div>
            </div>
          </div>

          <!-- Report Statistics -->
          <div class="card shadow">
            <div class="card-header py-3">
              <h6 class="m-0 fw-bold text-primary">Report Statistics</h6>
            </div>
            <div class="card-body">
              <div class="row text-center">
                <div class="col-6">
                  <div class="border-end">
                    <h4 class="text-primary mb-1">{{ reportStats.totalGenerated }}</h4>
                    <small class="text-muted">Total Reports</small>
                  </div>
                </div>
                <div class="col-6">
                  <h4 class="text-success mb-1">{{ reportStats.thisMonth }}</h4>
                  <small class="text-muted">This Month</small>
                </div>
              </div>
              <hr>
              <div class="row text-center">
                <div class="col-6">
                  <div class="border-end">
                    <h5 class="text-info mb-1">{{ reportStats.avgGenerationTime }}</h5>
                    <small class="text-muted">Avg Time</small>
                  </div>
                </div>
                <div class="col-6">
                  <h5 class="text-warning mb-1">{{ reportStats.mostUsedType }}</h5>
                  <small class="text-muted">Popular Type</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
      <!-- End Generated Reports Tab -->

      <!-- Receiving Reports Tab Content -->
      <div v-if="activeTab === 'receiving'">
        <div class="card shadow mb-4">
          <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 fw-bold text-primary">Receiving Reports</h6>
            <div class="d-flex align-items-center gap-2">
              <input class="form-control" placeholder="Search RR-..." v-model="receivingSearch" @input="fetchReceivingList" style="max-width: 240px;" />
              <select class="form-select" v-model="receivingStatus" @change="fetchReceivingList" style="max-width: 180px;">
                <option value="">All Status</option>
                <option value="DRAFT">Draft</option>
                <option value="COMPLETED">Completed</option>
                <option value="CANCELLED">Cancelled</option>
              </select>
              <button class="btn btn-outline-secondary" @click="fetchReceivingList" title="Refresh"><i class="bi bi-arrow-clockwise"></i></button>
            </div>
          </div>
          <div class="card-body">
            <div v-if="receivingLoading" class="text-center py-4">
              <div class="spinner-border text-primary" role="status">
                <span class="visually-hidden">Loading...</span>
              </div>
            </div>
            <div v-else class="table-responsive">
              <table class="table table-hover table-striped">
                <thead class="table-light">
                  <tr>
                    <th>Report #</th>
                    <th>Delivery Date</th>
                    <th>Delivered By</th>
                    <th>Received By</th>
                    <th>Total Items</th>
                    <th>Total Qty</th>
                    <th>Status</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="r in receivingList.items" :key="r.report_id" @click="goToViewReceiving(r)" style="cursor:pointer;">
                    <td class="fw-semibold">{{ r.report_number }}</td>
                    <td>{{ formatDate(r.delivery_date) }}</td>
                    <td>{{ r.delivered_by }}</td>
                    <td>{{ r.received_by_name || '-' }}</td>
                    <td>{{ r.total_items || 0 }}</td>
                    <td>{{ r.total_quantity || 0 }}</td>
                    <td>
                      <span class="badge" :class="getReceivingBadgeClass(r.status)">{{ r.status }}</span>
                    </td>
                    <td>
                      <div class="btn-group btn-group-sm">
                        <button class="btn btn-outline-primary" @click.stop="goToViewReceiving(r)"><i class="bi bi-eye"></i></button>
                        <button class="btn btn-outline-success" :disabled="r.status!=='DRAFT'" @click.stop="goToCompleteReceiving(r)"><i class="bi bi-check2-circle"></i></button>
                        <button class="btn btn-outline-danger" :disabled="r.status!=='DRAFT'" @click.stop="goToCancelReceiving(r)"><i class="bi bi-x-circle"></i></button>
                      </div>
                    </td>
                  </tr>
                  <tr v-if="(receivingList.items||[]).length===0">
                    <td colspan="8" class="text-center text-muted py-4">No receiving reports found</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- End Receiving Reports Tab -->

      <!-- Generate Report Modal -->
      <div class="modal fade" :class="{ show: showGenerateModal }" :style="{ display: showGenerateModal ? 'block' : 'none' }" tabindex="-1">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Generate New Report</h5>
              <button type="button" class="btn-close" @click="closeGenerateModal"></button>
            </div>
            <div class="modal-body">
              <form @submit.prevent="generateReport">
                <div class="row g-3">
                  <div class="col-md-6">
                    <label class="form-label">Report Type *</label>
                    <select class="form-select" v-model="generateForm.type" required>
                      <option value="">Select Type</option>
                      <option value="vaccination">Vaccination Report</option>
                      <option value="inventory">Inventory Report</option>
                      <option value="patient">Patient Report</option>
                      <option value="analytics">Analytics Report</option>
                    </select>
                  </div>
                  <div class="col-md-6">
                    <label class="form-label">Report Name *</label>
                    <input type="text" class="form-control" v-model="generateForm.name" required>
                  </div>
                  <div class="col-12">
                    <label class="form-label">Description</label>
                    <textarea class="form-control" rows="3" v-model="generateForm.description"></textarea>
                  </div>
                  <div class="col-md-6">
                    <label class="form-label">Start Date</label>
                    <DateInput v-model="generateForm.startDate" />
                  </div>
                  <div class="col-md-6">
                    <label class="form-label">End Date</label>
                    <DateInput v-model="generateForm.endDate" />
                  </div>
                  <div class="col-12">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" v-model="generateForm.includeCharts" id="includeCharts">
                      <label class="form-check-label" for="includeCharts">
                        Include charts and visualizations
                      </label>
                    </div>
                  </div>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" @click="closeGenerateModal">Cancel</button>
              <button type="button" class="btn btn-primary" @click="generateReport" :disabled="generating">
                <span v-if="generating" class="spinner-border spinner-border-sm me-2"></span>
                Generate Report
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Modal Backdrop -->
      <div v-if="showGenerateModal" class="modal-backdrop fade show"></div>

      <!-- Receiving modals removed: flows are page-based now -->
    </div>
  </AdminLayout>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useToast } from '@/composables/useToast'
import AdminLayout from '@/components/layout/AdminLayout.vue'
import DateInput from '@/components/common/DateInput.vue'
import AppPageHeader from '@/components/common/AppPageHeader.vue'
import AppPagination from '@/components/common/AppPagination.vue'
import api from '@/services/api'
import { nowPH, formatPHDate, formatPHDateTime, utcToPH, getCurrentPHISO } from '@/utils/dateUtils'

// Reactive data
const activeTab = ref('generated')
const loading = ref(true)
const generating = ref(false)
const reports = ref([])
const selectedDateRange = ref('last_30_days')
const selectedType = ref('')
const selectedStatus = ref('')
const currentPage = ref(1)
const itemsPerPage = ref(10)
const totalReports = ref(0)
const totalPages = ref(0)

// Modal states
const showGenerateModal = ref(false)

// Form data
const generateForm = ref({
  type: '',
  name: '',
  description: '',
  startDate: '',
  endDate: '',
  includeCharts: true
})

// Activity and stats
const recentActivity = ref([])
const reportStats = ref({
  totalGenerated: 0,
  thisMonth: 0,
  avgGenerationTime: '2.5s',
  mostUsedType: 'Vaccination'
})

// Receiving Reports state
const receivingLoading = ref(false)
const receivingList = ref({ items: [], totalCount: 0, totalPages: 0 })
const receivingStatus = ref('')
const receivingSearch = ref('')
const router = useRouter()

// Methods
const fetchReports = async () => {
  try {
    loading.value = true
    
    // Fetch different types of reports based on filters
    const reportPromises = []
    
    if (!selectedType.value || selectedType.value === 'vaccination') {
      // Fetch monthly report for current month
      const now = nowPH()
      reportPromises.push(
        api.get(`/reports/monthly?month=${now.month() + 1}&year=${now.year()}`)
          .then(response => ({
            id: `monthly-${now.year()}-${now.month() + 1}`,
            name: `Monthly Vaccination Report - ${now.format('MMMM YYYY')}`,
            description: 'Monthly vaccination statistics and summary',
            type: 'vaccination',
            status: 'completed',
            createdAt: getCurrentPHISO(),
            generatedBy: 'System',
            data: response.data.data
          }))
          .catch(() => null)
      )
    }
    
    if (!selectedType.value || selectedType.value === 'inventory') {
      // Fetch inventory low stock report
      reportPromises.push(
        api.get('/reports/low-stock')
          .then(response => ({
            id: 'inventory-low-stock',
            name: 'Inventory Low Stock Alert',
            description: 'Vaccines with low stock levels requiring attention',
            type: 'inventory',
            status: 'completed',
            createdAt: getCurrentPHISO(),
            generatedBy: 'System',
            data: response.data.data
          }))
          .catch(() => null)
      )
    }
    
    if (!selectedType.value || selectedType.value === 'patient') {
      // Fetch defaulters report
      reportPromises.push(
        api.get('/reports/defaulters')
          .then(response => ({
            id: 'defaulters-report',
            name: 'Defaulters Report',
            description: 'Patients who have missed their vaccination schedules',
            type: 'patient',
            status: 'completed',
            createdAt: new Date().toISOString(),
            generatedBy: 'System',
            data: response.data.data
          }))
          .catch(() => null)
      )
      
      // Fetch due soon report
      reportPromises.push(
        api.get('/reports/due-soon')
          .then(response => ({
            id: 'due-soon-report',
            name: 'Due Soon Report',
            description: 'Patients with upcoming vaccination schedules',
            type: 'patient',
            status: 'completed',
            createdAt: new Date().toISOString(),
            generatedBy: 'System',
            data: response.data.data
          }))
          .catch(() => null)
      )
    }
    
    if (!selectedType.value || selectedType.value === 'analytics') {
      // Fetch TCL report
      reportPromises.push(
        api.get('/reports/tcl')
          .then(response => ({
            id: 'tcl-report',
            name: 'Target Client List',
            description: 'Complete list of patients eligible for vaccination programs',
            type: 'analytics',
            status: 'completed',
            createdAt: new Date().toISOString(),
            generatedBy: 'System',
            data: response.data.data
          }))
          .catch(() => null)
      )
    }
    
    const reportResults = await Promise.all(reportPromises)
    const validReports = reportResults.filter(report => report !== null)
    
    reports.value = validReports
    totalReports.value = validReports.length
    totalPages.value = Math.ceil(totalReports.value / itemsPerPage.value)
    
    // Update report statistics
    reportStats.value = {
      totalGenerated: validReports.length,
      thisMonth: validReports.length,
      avgGenerationTime: '1.2s',
      mostUsedType: 'vaccination'
    }
    
    // Fetch recent activity from activity logs
    try {
      const activityResponse = await api.get('/activity-logs?limit=5')
      recentActivity.value = activityResponse.data.data?.map(activity => ({
        id: activity.log_id,
        description: activity.description,
        icon: getActivityIcon(activity.action_type),
        timestamp: activity.timestamp
      })) || []
    } catch {
      recentActivity.value = []
    }

  } catch (error) {
    console.error('Error fetching reports:', error)
    reports.value = []
    totalReports.value = 0
    totalPages.value = 0
  } finally {
    loading.value = false
  }
}

const generateQuickReport = async (type) => {
  try {
    generating.value = true
    
    let endpoint = ''
    let reportName = ''
    let description = ''
    
    switch (type) {
      case 'vaccination_summary':
        endpoint = '/reports/monthly'
        const now = nowPH()
        endpoint += `?month=${now.month() + 1}&year=${now.year()}`
        reportName = `Vaccination Summary Report - ${now.format('MMMM YYYY')}`
        description = 'Current month vaccination statistics and summary'
        break
      case 'inventory_status':
        endpoint = '/reports/low-stock'
        reportName = 'Inventory Status Report'
        description = 'Current vaccine inventory levels and low stock alerts'
        break
      case 'patient_stats':
        endpoint = '/reports/defaulters'
        reportName = 'Patient Statistics Report'
        description = 'Patient vaccination compliance and defaulter analysis'
        break
      case 'monthly_report':
        endpoint = '/reports/monthly'
        const currentMonth = nowPH()
        endpoint += `?month=${currentMonth.month() + 1}&year=${currentMonth.year()}`
        reportName = `Monthly Activity Report - ${currentMonth.format('MMMM YYYY')}`
        description = 'Comprehensive monthly vaccination and activity report'
        break
      case 'compliance_report':
        endpoint = '/reports/due-soon'
        reportName = 'Compliance Report'
        description = 'Upcoming vaccinations and compliance tracking'
        break
      default:
        throw new Error('Unknown report type')
    }
    
    const response = await api.get(endpoint)
    
    const newReport = {
      id: `${type}-${nowPH().valueOf()}`,
      name: reportName,
      description: description,
      type: type.split('_')[0],
      status: 'completed',
      createdAt: getCurrentPHISO(),
      generatedBy: 'Current User',
      data: response.data.data
    }
    
    reports.value.unshift(newReport)
    totalReports.value++
    
    const { addToast } = useToast()
    addToast({ title: 'Success', message: 'Report generated successfully', type: 'success' })
    
  } catch (error) {
    console.error('Error generating quick report:', error)
    const { addToast } = useToast()
    addToast({ title: 'Error', message: 'Failed to generate report', type: 'error' })
  } finally {
    generating.value = false
  }
}

const generateReport = async () => {
  try {
    generating.value = true
    
    // Map frontend report types to backend endpoints
    let endpoint = ''
    const params = {}
    
    switch (generateForm.value.type) {
      case 'vaccination':
        endpoint = '/reports/monthly'
        const now = nowPH()
        params.month = now.month() + 1
        params.year = now.year()
        break
      case 'inventory':
        endpoint = '/reports/low-stock'
        break
      case 'patient':
        endpoint = '/reports/defaulters'
        break
      case 'analytics':
        endpoint = '/reports/tcl'
        break
      default:
        throw new Error('Unsupported report type')
    }
    
    const response = await api.get(endpoint, { params })
    
    const newReport = {
      id: `custom-${nowPH().valueOf()}`,
      name: generateForm.value.name,
      description: generateForm.value.description,
      type: generateForm.value.type,
      status: 'completed',
      createdAt: getCurrentPHISO(),
      generatedBy: 'Current User',
      data: response.data.data
    }
    
    reports.value.unshift(newReport)
    totalReports.value++
    
    closeGenerateModal()
    
    const { addToast } = useToast()
    addToast({ title: 'Success', message: 'Report generated successfully', type: 'success' })
    
  } catch (error) {
    console.error('Error generating report:', error)
    const { addToast } = useToast()
    addToast({ title: 'Error', message: 'Error generating report', type: 'error' })
  } finally {
    generating.value = false
  }
}

const changePage = (page) => {
  currentPage.value = page
  fetchReports()
}

const applyFilters = () => {
  currentPage.value = 1
  fetchReports()
}

const resetFilters = () => {
  selectedDateRange.value = 'last_30_days'
  selectedType.value = ''
  selectedStatus.value = ''
  currentPage.value = 1
  fetchReports()
}

const refreshReports = () => {
  fetchReports()
}

const closeGenerateModal = () => {
  showGenerateModal.value = false
  generateForm.value = {
    type: '',
    name: '',
    description: '',
    startDate: '',
    endDate: '',
    includeCharts: true
  }
}

const downloadReport = (report) => {
  try {
    // Convert report data to CSV format
    if (report.data && Array.isArray(report.data)) {
      const csvContent = convertToCSV(report.data)
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
      const link = document.createElement('a')
      
      if (link.download !== undefined) {
        const url = URL.createObjectURL(blob)
        link.setAttribute('href', url)
        link.setAttribute('download', `${report.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.csv`)
        link.style.visibility = 'hidden'
        document.body.appendChild(link)
        link.click()
        document.body.removeChild(link)
      }
      
      const { addToast } = useToast()
      addToast({ title: 'Success', message: 'Report downloaded successfully', type: 'success' })
    } else {
      throw new Error('No data available for download')
    }
  } catch (error) {
    console.error('Error downloading report:', error)
    const { addToast } = useToast()
    addToast({ title: 'Error', message: 'Failed to download report', type: 'error' })
  }
}

const viewReport = (report) => {
  // For now, show the data in a modal or console
  console.log('Report Data:', report)
  
  // You could implement a modal to show the report data here
  // For now, we'll just show a toast
  const { addToast } = useToast()
  addToast({ title: 'Report Data', message: `Viewing ${report.name} - Check console for data`, type: 'info' })
}

const shareReport = (report) => {
  console.log('Sharing report:', report.name)
  // Implement share functionality
}

const deleteReport = async (report) => {
  if (confirm(`Are you sure you want to delete "${report.name}"?`)) {
    reports.value = reports.value.filter(r => r.id !== report.id)
    totalReports.value--
  }
}

// Utility functions
const formatDate = (dateString) => {
  if (!dateString) return ''
  return formatPHDate(dateString)
}

const formatTime = (dateString) => {
  if (!dateString) return ''
  return formatPHDateTime(dateString, 'hh:mm A')
}

const formatTimeAgo = (dateString) => {
  if (!dateString) return ''
  const now = nowPH()
  const date = utcToPH(dateString)
  const diffInHours = now.diff(date, 'hours')

  if (diffInHours < 1) return 'Just now'
  if (diffInHours < 24) return `${diffInHours}h ago`
  const diffInDays = Math.floor(diffInHours / 24)
  return `${diffInDays}d ago`
}

const getTypeBadgeClass = (type) => {
  const classes = {
    vaccination: 'bg-primary',
    inventory: 'bg-success',
    patient: 'bg-info',
    analytics: 'bg-warning text-dark'
  }
  return classes[type] || 'bg-secondary'
}

const getStatusBadgeClass = (status) => {
  const classes = {
    completed: 'bg-success',
    generating: 'bg-primary',
    failed: 'bg-danger'
  }
  return classes[status] || 'bg-secondary'
}

const convertToCSV = (data) => {
  if (!data || data.length === 0) return ''
  
  const headers = Object.keys(data[0])
  const csvRows = []
  
  // Add headers
  csvRows.push(headers.join(','))
  
  // Add data rows
  data.forEach(row => {
    const values = headers.map(header => {
      const value = row[header]
      // Handle null/undefined values and escape commas/quotes
      if (value === null || value === undefined) return ''
      const stringValue = String(value)
      if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
        return `"${stringValue.replace(/"/g, '""')}"`
      }
      return stringValue
    })
    csvRows.push(values.join(','))
  })
  
  return csvRows.join('\n')
}

const getActivityIcon = (actionType) => {
  const iconMap = {
    'CREATE': 'bi bi-plus-circle',
    'UPDATE': 'bi bi-pencil',
    'DELETE': 'bi bi-trash',
    'LOGIN': 'bi bi-box-arrow-in-right',
    'LOGOUT': 'bi bi-box-arrow-left'
  }
  return iconMap[actionType] || 'bi bi-circle'
}

const getStatusIcon = (status) => {
  const iconMap = {
    'completed': 'bi bi-check-circle',
    'generating': 'bi bi-arrow-repeat',
    'failed': 'bi bi-exclamation-circle'
  }
  return iconMap[status] || 'bi bi-circle'
}

// Receiving Reports Methods
const fetchReceivingList = async () => {
  console.log('Fetching receiving reports...', { status: receivingStatus.value, search: receivingSearch.value })
  receivingLoading.value = true
  try {
    const { data } = await api.get('/receiving-reports', { 
      params: { 
        status: receivingStatus.value, 
        search: receivingSearch.value, 
        page: 1, 
        limit: 20 
      } 
    })
    console.log('Receiving reports API response:', data)
    receivingList.value = data.data || data
    console.log('Receiving list after assignment:', receivingList.value)
  } catch (e) {
    console.error('Failed to load receiving reports', e)
    console.error('Error response:', e.response?.data)
    receivingList.value = { items: [], totalCount: 0, totalPages: 0 }
  } finally {
    receivingLoading.value = false
  }
}

// Navigation helpers for Receiving Reports page-based flows
const goToCreateReceiving = () => router.push({ name: 'ReceivingReportNew' })
const goToViewReceiving = (r) => router.push({ name: 'ReceivingReportView', params: { id: r.report_id } })
const goToCompleteReceiving = (r) => router.push({ name: 'ReceivingReportView', params: { id: r.report_id }, query: { action: 'complete' } })
const goToCancelReceiving = (r) => router.push({ name: 'ReceivingReportView', params: { id: r.report_id }, query: { action: 'cancel' } })

const getReceivingBadgeClass = (status) => {
  const classes = {
    'DRAFT': 'bg-secondary',
    'COMPLETED': 'bg-success',
    'CANCELLED': 'bg-danger'
  }
  return classes[status] || 'bg-secondary'
}

// Lifecycle
onMounted(() => {
  fetchReports()
  // If user directly navigates to receiving reports tab, fetch that data too
  if (activeTab.value === 'receiving') {
    fetchReceivingList()
  }
})

// Watch for tab changes
watch(activeTab, (newTab) => {
  if (newTab === 'receiving' && receivingList.value.items.length === 0) {
    fetchReceivingList()
  }
})
</script>

<style scoped>
.timeline-marker {
  width: 24px;
  height: 24px;
  border-radius: 50%;
  background: #f8f9fa;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 2px solid #dee2e6;
}

.modal.show {
  background-color: rgba(0, 0, 0, 0.5);
}

.btn-group .btn {
  border-radius: 0.25rem;
  margin-right: 0.125rem;
}

.btn-group .btn:last-child {
  margin-right: 0;
}

.text-sm {
  font-size: 0.875rem;
}
</style>
