-- Potential index issues: invalid, unused (low scans), and duplicates by definition
WITH idx AS (
  SELECT n.nspname AS schema, t.relname AS table_name, i.relname AS index_name,
         pg_get_indexdef(ix.indexrelid) AS def, ix.indisvalid, ix.indisunique, ix.indisprimary
  FROM pg_index ix
  JOIN pg_class t ON t.oid = ix.indrelid
  JOIN pg_class i ON i.oid = ix.indexrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname NOT IN ('pg_catalog','information_schema')
    AND n.nspname = 'public' -- Limit to public schema only
), stats AS (
  SELECT n.nspname AS schema, c.relname AS index_name, s.idx_scan
  FROM pg_stat_user_indexes s
  JOIN pg_class c ON c.oid = s.indexrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' -- Limit to public schema only
)
SELECT 'invalid' AS issue, idx.schema, idx.table_name, idx.index_name, idx.def, NULL::text AS extra
FROM idx WHERE NOT indisvalid
UNION ALL
SELECT 'unused_low_scan', idx.schema, idx.table_name, idx.index_name, idx.def, COALESCE(stats.idx_scan,0)::text
FROM idx LEFT JOIN stats ON stats.schema = idx.schema AND stats.index_name = idx.index_name
WHERE COALESCE(stats.idx_scan,0) = 0 AND NOT idx.indisprimary
UNION ALL
SELECT 'duplicate_def', a.schema, a.table_name, a.index_name, a.def, 'duplicate_of='||b.index_name
FROM idx a
JOIN idx b ON a.schema = b.schema AND a.table_name = b.table_name AND a.index_name <> b.index_name AND a.def = b.def
ORDER BY issue, schema, table_name, index_name;

| issue           | schema | table_name                  | index_name                                           | def                                                                                                                                                                                                                                                                            | extra |
| --------------- | ------ | --------------------------- | ---------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ----- |
| unused_low_scan | public | conversationparticipants    | idx_conversationparticipants_user_active             | CREATE INDEX idx_conversationparticipants_user_active ON public.conversationparticipants USING btree (user_id) WHERE (is_deleted = false)                                                                                                                                      | 0     |
| unused_low_scan | public | defaulters_mv               | idx_defaulters_overdue_count                         | CREATE INDEX idx_defaulters_overdue_count ON public.defaulters_mv USING btree (overdue_count DESC)                                                                                                                                                                             | 0     |
| unused_low_scan | public | deworming                   | idx_deworming_inventory_active                       | CREATE INDEX idx_deworming_inventory_active ON public.deworming USING btree (inventory_id) WHERE (is_deleted = false)                                                                                                                                                          | 0     |
| unused_low_scan | public | deworming                   | idx_deworming_outside_flag                           | CREATE INDEX idx_deworming_outside_flag ON public.deworming USING btree (outside) WHERE (is_deleted = false)                                                                                                                                                                   | 0     |
| unused_low_scan | public | deworming                   | idx_deworming_patient_active                         | CREATE INDEX idx_deworming_patient_active ON public.deworming USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                              | 0     |
| unused_low_scan | public | deworming                   | idx_deworming_vaccine_active                         | CREATE INDEX idx_deworming_vaccine_active ON public.deworming USING btree (vaccine_id) WHERE (is_deleted = false)                                                                                                                                                              | 0     |
| unused_low_scan | public | deworming                   | idx_deworming_visit_active                           | CREATE INDEX idx_deworming_visit_active ON public.deworming USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                                  | 0     |
| unused_low_scan | public | deworming                   | idx_deworming_vital_active                           | CREATE INDEX idx_deworming_vital_active ON public.deworming USING btree (vital_id) WHERE (is_deleted = false)                                                                                                                                                                  | 0     |
| unused_low_scan | public | deworming_history           | deworming_history_deworming_id_version_no_idx        | CREATE INDEX deworming_history_deworming_id_version_no_idx ON public.deworming_history USING btree (deworming_id, version_no DESC)                                                                                                                                             | 0     |
| unused_low_scan | public | guardian_auto_send_settings | guardian_auto_send_settings_guardian_id_key          | CREATE UNIQUE INDEX guardian_auto_send_settings_guardian_id_key ON public.guardian_auto_send_settings USING btree (guardian_id)                                                                                                                                                | 0     |
| unused_low_scan | public | guardian_auto_send_settings | idx_guardian_auto_send_created_by                    | CREATE INDEX idx_guardian_auto_send_created_by ON public.guardian_auto_send_settings USING btree (created_by)                                                                                                                                                                  | 0     |
| unused_low_scan | public | guardian_auto_send_settings | idx_guardian_auto_send_deleted_by                    | CREATE INDEX idx_guardian_auto_send_deleted_by ON public.guardian_auto_send_settings USING btree (deleted_by)                                                                                                                                                                  | 0     |
| unused_low_scan | public | guardian_auto_send_settings | idx_guardian_auto_send_enabled                       | CREATE INDEX idx_guardian_auto_send_enabled ON public.guardian_auto_send_settings USING btree (auto_send_enabled)                                                                                                                                                              | 0     |
| unused_low_scan | public | guardian_auto_send_settings | idx_guardian_auto_send_guardian_id                   | CREATE INDEX idx_guardian_auto_send_guardian_id ON public.guardian_auto_send_settings USING btree (guardian_id)                                                                                                                                                                | 0     |
| unused_low_scan | public | guardian_auto_send_settings | idx_guardian_auto_send_is_deleted                    | CREATE INDEX idx_guardian_auto_send_is_deleted ON public.guardian_auto_send_settings USING btree (is_deleted)                                                                                                                                                                  | 0     |
| unused_low_scan | public | guardian_auto_send_settings | idx_guardian_auto_send_updated_by                    | CREATE INDEX idx_guardian_auto_send_updated_by ON public.guardian_auto_send_settings USING btree (updated_by)                                                                                                                                                                  | 0     |
| unused_low_scan | public | guardians                   | guardians_contact_number_key                         | CREATE UNIQUE INDEX guardians_contact_number_key ON public.guardians USING btree (contact_number)                                                                                                                                                                              | 0     |
| unused_low_scan | public | guardians                   | guardians_user_id_uniq                               | CREATE UNIQUE INDEX guardians_user_id_uniq ON public.guardians USING btree (user_id) WHERE (COALESCE(is_deleted, false) = false)                                                                                                                                               | 0     |
| unused_low_scan | public | immunizations               | idx_immunizations_inventory_active                   | CREATE INDEX idx_immunizations_inventory_active ON public.immunizations USING btree (inventory_id) WHERE (is_deleted = false)                                                                                                                                                  | 0     |
| unused_low_scan | public | immunizations               | idx_immunizations_outside_flag                       | CREATE INDEX idx_immunizations_outside_flag ON public.immunizations USING btree (outside) WHERE (is_deleted = false)                                                                                                                                                           | 0     |
| unused_low_scan | public | immunizations               | idx_immunizations_visit_active                       | CREATE INDEX idx_immunizations_visit_active ON public.immunizations USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                          | 0     |
| unused_low_scan | public | immunizations               | idx_immunizations_vital_active                       | CREATE INDEX idx_immunizations_vital_active ON public.immunizations USING btree (vital_id) WHERE (is_deleted = false)                                                                                                                                                          | 0     |
| unused_low_scan | public | immunizations_history       | idx_immunizations_history_changed_fields             | CREATE INDEX idx_immunizations_history_changed_fields ON public.immunizations_history USING gin (changed_fields)                                                                                                                                                               | 0     |
| unused_low_scan | public | inventory                   | ux_inventory_identity_active                         | CREATE UNIQUE INDEX ux_inventory_identity_active ON public.inventory USING btree (vaccine_id, lot_number, expiration_date, COALESCE(storage_location, ''::text)) WHERE (is_deleted = false)                                                                                    | 0     |
| unused_low_scan | public | inventory_requests          | idx_inventory_requests_status                        | CREATE INDEX idx_inventory_requests_status ON public.inventory_requests USING btree (status, requested_at)                                                                                                                                                                     | 0     |
| unused_low_scan | public | inventory_requests_history  | inventory_requests_history_request_id_version_no_idx | CREATE INDEX inventory_requests_history_request_id_version_no_idx ON public.inventory_requests_history USING btree (request_id, version_no DESC)                                                                                                                               | 0     |
| unused_low_scan | public | messages                    | idx_messages_conversation_created                    | CREATE INDEX idx_messages_conversation_created ON public.messages USING btree (conversation_id, created_at DESC NULLS LAST)                                                                                                                                                    | 0     |
| unused_low_scan | public | messages                    | idx_messages_conversation_time                       | CREATE INDEX idx_messages_conversation_time ON public.messages USING btree (conversation_id, created_at DESC) WHERE (is_deleted = false)                                                                                                                                       | 0     |
| unused_low_scan | public | messages                    | idx_messages_conversation_ts                         | CREATE INDEX idx_messages_conversation_ts ON public.messages USING btree (conversation_id, created_at DESC)                                                                                                                                                                    | 0     |
| unused_low_scan | public | messages                    | idx_messages_conversation_unread                     | CREATE INDEX idx_messages_conversation_unread ON public.messages USING btree (conversation_id) WHERE ((read_at IS NULL) AND (is_deleted = false))                                                                                                                              | 0     |
| unused_low_scan | public | messages                    | idx_messages_sender_ts                               | CREATE INDEX idx_messages_sender_ts ON public.messages USING btree (sender_id, created_at DESC)                                                                                                                                                                                | 0     |
| unused_low_scan | public | notifications               | idx_notifications_channel                            | CREATE INDEX idx_notifications_channel ON public.notifications USING btree (channel)                                                                                                                                                                                           | 0     |
| unused_low_scan | public | notifications               | idx_notifications_created_at                         | CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at)                                                                                                                                                                                     | 0     |
| unused_low_scan | public | notifications               | idx_notifications_recipient_user_id                  | CREATE INDEX idx_notifications_recipient_user_id ON public.notifications USING btree (recipient_user_id)                                                                                                                                                                       | 0     |
| unused_low_scan | public | notifications               | idx_notifications_scheduled_at                       | CREATE INDEX idx_notifications_scheduled_at ON public.notifications USING btree (scheduled_at)                                                                                                                                                                                 | 0     |
| unused_low_scan | public | notifications               | idx_notifications_status                             | CREATE INDEX idx_notifications_status ON public.notifications USING btree (status)                                                                                                                                                                                             | 0     |
| unused_low_scan | public | notifications               | idx_notifications_status_time                        | CREATE INDEX idx_notifications_status_time ON public.notifications USING btree (status, scheduled_at) WHERE (is_deleted = false)                                                                                                                                               | 0     |
| unused_low_scan | public | notifications               | idx_notifications_status_ts                          | CREATE INDEX idx_notifications_status_ts ON public.notifications USING btree (status, created_at DESC)                                                                                                                                                                         | 0     |
| unused_low_scan | public | notifications               | idx_notifications_unread                             | CREATE INDEX idx_notifications_unread ON public.notifications USING btree (recipient_user_id) WHERE ((read_at IS NULL) AND (is_deleted = false))                                                                                                                               | 0     |
| unused_low_scan | public | patients                    | idx_patients_active_name                             | CREATE INDEX idx_patients_active_name ON public.patients USING btree (firstname, middlename, surname) WHERE (is_deleted = false)                                                                                                                                               | 0     |
| unused_low_scan | public | patients                    | idx_patients_full_name_trgm                          | CREATE INDEX idx_patients_full_name_trgm ON public.patients USING gin (full_name gin_trgm_ops) WHERE (is_deleted = false)                                                                                                                                                      | 0     |
| unused_low_scan | public | patients_history            | idx_patients_history_changed_fields                  | CREATE INDEX idx_patients_history_changed_fields ON public.patients_history USING gin (changed_fields)                                                                                                                                                                         | 0     |
| unused_low_scan | public | patientschedule             | idx_patientschedule_overdue                          | CREATE INDEX idx_patientschedule_overdue ON public.patientschedule USING btree (patient_id, scheduled_date) WHERE (((status)::text = ANY ((ARRAY['Scheduled'::character varying, 'Due'::character varying, 'Overdue'::character varying])::text[])) AND (actual_date IS NULL)) | 0     |
| unused_low_scan | public | patientschedule_history     | idx_ps_history_changed_fields                        | CREATE INDEX idx_ps_history_changed_fields ON public.patientschedule_history USING gin (changed_fields)                                                                                                                                                                        | 0     |
| unused_low_scan | public | receiving_report_items      | idx_receiving_report_items_inventory_id              | CREATE INDEX idx_receiving_report_items_inventory_id ON public.receiving_report_items USING btree (inventory_id)                                                                                                                                                               | 0     |
| unused_low_scan | public | receiving_report_items      | idx_receiving_report_items_vaccine_id                | CREATE INDEX idx_receiving_report_items_vaccine_id ON public.receiving_report_items USING btree (vaccine_id)                                                                                                                                                                   | 0     |
| unused_low_scan | public | receiving_reports           | idx_receiving_reports_status                         | CREATE INDEX idx_receiving_reports_status ON public.receiving_reports USING btree (status)                                                                                                                                                                                     | 0     |
| unused_low_scan | public | receiving_reports           | receiving_reports_report_number_key                  | CREATE UNIQUE INDEX receiving_reports_report_number_key ON public.receiving_reports USING btree (report_number)                                                                                                                                                                | 0     |
| unused_low_scan | public | schedule_doses              | schedule_doses_schedule_id_dose_number_key           | CREATE UNIQUE INDEX schedule_doses_schedule_id_dose_number_key ON public.schedule_doses USING btree (schedule_id, dose_number)                                                                                                                                                 | 0     |
| unused_low_scan | public | schedule_master             | idx_schedule_master_vaccine                          | CREATE INDEX idx_schedule_master_vaccine ON public.schedule_master USING btree (vaccine_id)                                                                                                                                                                                    | 0     |
| unused_low_scan | public | sms_logs                    | idx_sms_logs_created_by                              | CREATE INDEX idx_sms_logs_created_by ON public.sms_logs USING btree (created_by)                                                                                                                                                                                               | 0     |
| unused_low_scan | public | sms_logs                    | idx_sms_logs_deleted_by                              | CREATE INDEX idx_sms_logs_deleted_by ON public.sms_logs USING btree (deleted_by)                                                                                                                                                                                               | 0     |
| unused_low_scan | public | sms_logs                    | idx_sms_logs_guardian_id                             | CREATE INDEX idx_sms_logs_guardian_id ON public.sms_logs USING btree (guardian_id)                                                                                                                                                                                             | 0     |
| unused_low_scan | public | sms_logs                    | idx_sms_logs_is_deleted                              | CREATE INDEX idx_sms_logs_is_deleted ON public.sms_logs USING btree (is_deleted)                                                                                                                                                                                               | 0     |
| unused_low_scan | public | sms_logs                    | idx_sms_logs_patient_id                              | CREATE INDEX idx_sms_logs_patient_id ON public.sms_logs USING btree (patient_id)                                                                                                                                                                                               | 0     |
| unused_low_scan | public | sms_logs                    | idx_sms_logs_phone_number                            | CREATE INDEX idx_sms_logs_phone_number ON public.sms_logs USING btree (phone_number)                                                                                                                                                                                           | 0     |
| unused_low_scan | public | sms_logs                    | idx_sms_logs_status                                  | CREATE INDEX idx_sms_logs_status ON public.sms_logs USING btree (status)                                                                                                                                                                                                       | 0     |
| unused_low_scan | public | sms_logs                    | idx_sms_logs_type                                    | CREATE INDEX idx_sms_logs_type ON public.sms_logs USING btree (type)                                                                                                                                                                                                           | 0     |
| unused_low_scan | public | sms_logs                    | idx_sms_logs_updated_by                              | CREATE INDEX idx_sms_logs_updated_by ON public.sms_logs USING btree (updated_by)                                                                                                                                                                                               | 0     |
| unused_low_scan | public | sms_templates               | idx_sms_templates_created_by                         | CREATE INDEX idx_sms_templates_created_by ON public.sms_templates USING btree (created_by)                                                                                                                                                                                     | 0     |
| unused_low_scan | public | sms_templates               | idx_sms_templates_deleted_by                         | CREATE INDEX idx_sms_templates_deleted_by ON public.sms_templates USING btree (deleted_by)                                                                                                                                                                                     | 0     |
| unused_low_scan | public | sms_templates               | idx_sms_templates_is_active                          | CREATE INDEX idx_sms_templates_is_active ON public.sms_templates USING btree (is_active)                                                                                                                                                                                       | 0     |
| unused_low_scan | public | sms_templates               | idx_sms_templates_is_deleted                         | CREATE INDEX idx_sms_templates_is_deleted ON public.sms_templates USING btree (is_deleted)                                                                                                                                                                                     | 0     |
| unused_low_scan | public | sms_templates               | idx_sms_templates_trigger_type                       | CREATE INDEX idx_sms_templates_trigger_type ON public.sms_templates USING btree (trigger_type)                                                                                                                                                                                 | 0     |
| unused_low_scan | public | sms_templates               | idx_sms_templates_updated_by                         | CREATE INDEX idx_sms_templates_updated_by ON public.sms_templates USING btree (updated_by)                                                                                                                                                                                     | 0     |
| unused_low_scan | public | user_sessions               | idx_user_sessions_last_activity                      | CREATE INDEX idx_user_sessions_last_activity ON public.user_sessions USING btree (last_activity DESC)                                                                                                                                                                          | 0     |
| unused_low_scan | public | users                       | idx_users_contact_number                             | CREATE INDEX idx_users_contact_number ON public.users USING btree (contact_number)                                                                                                                                                                                             | 0     |
| unused_low_scan | public | users                       | idx_users_email_lower                                | CREATE INDEX idx_users_email_lower ON public.users USING btree (lower((email)::text))                                                                                                                                                                                          | 0     |
| unused_low_scan | public | users                       | idx_users_full_name_trgm                             | CREATE INDEX idx_users_full_name_trgm ON public.users USING gin (full_name gin_trgm_ops) WHERE (is_deleted = false)                                                                                                                                                            | 0     |
| unused_low_scan | public | users                       | idx_users_role_status                                | CREATE INDEX idx_users_role_status ON public.users USING btree (role, user_status) WHERE (is_deleted = false)                                                                                                                                                                  | 0     |
| unused_low_scan | public | users                       | idx_users_status                                     | CREATE INDEX idx_users_status ON public.users USING btree (user_status) WHERE (is_deleted = false)                                                                                                                                                                             | 0     |
| unused_low_scan | public | users                       | idx_users_username_lower                             | CREATE INDEX idx_users_username_lower ON public.users USING btree (lower((username)::text))                                                                                                                                                                                    | 0     |
| unused_low_scan | public | users_history               | idx_users_history_changed_fields                     | CREATE INDEX idx_users_history_changed_fields ON public.users_history USING gin (changed_fields)                                                                                                                                                                               | 0     |
| unused_low_scan | public | vaccinemaster               | uq_vaccinemaster_antigen_brand                       | CREATE UNIQUE INDEX uq_vaccinemaster_antigen_brand ON public.vaccinemaster USING btree (antigen_name, brand_name) WHERE (is_deleted = false)                                                                                                                                   | 0     |
| unused_low_scan | public | vaccinemaster               | uq_vaccinemaster_antigen_brand_active                | CREATE UNIQUE INDEX uq_vaccinemaster_antigen_brand_active ON public.vaccinemaster USING btree (lower((antigen_name)::text), lower((COALESCE(brand_name, ''::character varying))::text)) WHERE (is_deleted = false)                                                             | 0     |
| unused_low_scan | public | visits                      | idx_visits_patient_active                            | CREATE INDEX idx_visits_patient_active ON public.visits USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                                    | 0     |
| unused_low_scan | public | vitalsigns                  | idx_vitalsigns_visit_active                          | CREATE INDEX idx_vitalsigns_visit_active ON public.vitalsigns USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                                | 0     |
| unused_low_scan | public | vitamina                    | idx_vitamina_inventory_active                        | CREATE INDEX idx_vitamina_inventory_active ON public.vitamina USING btree (inventory_id) WHERE (is_deleted = false)                                                                                                                                                            | 0     |
| unused_low_scan | public | vitamina                    | idx_vitamina_outside_flag                            | CREATE INDEX idx_vitamina_outside_flag ON public.vitamina USING btree (outside) WHERE (is_deleted = false)                                                                                                                                                                     | 0     |
| unused_low_scan | public | vitamina                    | idx_vitamina_patient_active                          | CREATE INDEX idx_vitamina_patient_active ON public.vitamina USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                                | 0     |
| unused_low_scan | public | vitamina                    | idx_vitamina_vaccine_active                          | CREATE INDEX idx_vitamina_vaccine_active ON public.vitamina USING btree (vaccine_id) WHERE (is_deleted = false)                                                                                                                                                                | 0     |
| unused_low_scan | public | vitamina                    | idx_vitamina_visit_active                            | CREATE INDEX idx_vitamina_visit_active ON public.vitamina USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                                    | 0     |
| unused_low_scan | public | vitamina                    | idx_vitamina_vital_active                            | CREATE INDEX idx_vitamina_vital_active ON public.vitamina USING btree (vital_id) WHERE (is_deleted = false)                                                                                                                                                                    | 0     |
| unused_low_scan | public | vitamina_history            | vitamina_history_vitamina_id_version_no_idx          | CREATE INDEX vitamina_history_vitamina_id_version_no_idx ON public.vitamina_history USING btree (vitamina_id, version_no DESC)                                                                                                                                                 | 0     |