-- Migration: Add `faqs` table and `message_receipts` table

BEGIN;

-- 1) faqs table
CREATE TABLE IF NOT EXISTS faqs (
  faq_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  tags JSONB DEFAULT '[]'::jsonb,
  is_deleted BOOLEAN DEFAULT FALSE,
  deleted_at TIMESTAMP WITHOUT TIME ZONE,
  deleted_by BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_by BIGINT,
  updated_at TIMESTAMP WITH TIME ZONE,
  updated_by BIGINT
);

-- 2) message_receipts table (per-recipient deliver/read tracking)
CREATE TABLE IF NOT EXISTS message_receipts (
  receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT NOT NULL REFERENCES messages(message_id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL,
  delivered_at TIMESTAMP WITH TIME ZONE,
  read_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE (message_id, user_id)
);

-- Optional: index to quickly query unread messages per user
CREATE INDEX IF NOT EXISTS idx_message_receipts_user_unread ON message_receipts(user_id, read_at) WHERE read_at IS NULL;

COMMIT;
