-- Potential index issues: invalid, unused (low scans), and duplicates by definition
WITH idx AS (
  SELECT n.nspname AS schema, t.relname AS table_name, i.relname AS index_name,
         pg_get_indexdef(ix.indexrelid) AS def, ix.indisvalid, ix.indisunique, ix.indisprimary
  FROM pg_index ix
  JOIN pg_class t ON t.oid = ix.indrelid
  JOIN pg_class i ON i.oid = ix.indexrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname NOT IN ('pg_catalog','information_schema')
), stats AS (
  SELECT n.nspname AS schema, c.relname AS index_name, s.idx_scan
  FROM pg_stat_user_indexes s
  JOIN pg_class c ON c.oid = s.indexrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
)
SELECT 'invalid' AS issue, idx.schema, idx.table_name, idx.index_name, idx.def, NULL::text AS extra
FROM idx WHERE NOT indisvalid
UNION ALL
SELECT 'unused_low_scan', idx.schema, idx.table_name, idx.index_name, idx.def, COALESCE(stats.idx_scan,0)::text
FROM idx LEFT JOIN stats ON stats.schema = idx.schema AND stats.index_name = idx.index_name
WHERE COALESCE(stats.idx_scan,0) = 0 AND NOT idx.indisprimary
UNION ALL
SELECT 'duplicate_def', a.schema, a.table_name, a.index_name, a.def, 'duplicate_of='||b.index_name
FROM idx a
JOIN idx b ON a.schema = b.schema AND a.table_name = b.table_name AND a.index_name <> b.index_name AND a.def = b.def
ORDER BY issue, schema, table_name, index_name;

| issue           | schema   | table_name                 | index_name                                           | def                                                                                                                                                                                                                                                                            | extra |
| --------------- | -------- | -------------------------- | ---------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ----- |
| unused_low_scan | auth     | audit_log_entries          | audit_logs_instance_id_idx                           | CREATE INDEX audit_logs_instance_id_idx ON auth.audit_log_entries USING btree (instance_id)                                                                                                                                                                                    | 0     |
| unused_low_scan | auth     | flow_state                 | flow_state_created_at_idx                            | CREATE INDEX flow_state_created_at_idx ON auth.flow_state USING btree (created_at DESC)                                                                                                                                                                                        | 0     |
| unused_low_scan | auth     | flow_state                 | idx_auth_code                                        | CREATE INDEX idx_auth_code ON auth.flow_state USING btree (auth_code)                                                                                                                                                                                                          | 0     |
| unused_low_scan | auth     | flow_state                 | idx_user_id_auth_method                              | CREATE INDEX idx_user_id_auth_method ON auth.flow_state USING btree (user_id, authentication_method)                                                                                                                                                                           | 0     |
| unused_low_scan | auth     | identities                 | identities_provider_id_provider_unique               | CREATE UNIQUE INDEX identities_provider_id_provider_unique ON auth.identities USING btree (provider_id, provider)                                                                                                                                                              | 0     |
| unused_low_scan | auth     | mfa_challenges             | mfa_challenge_created_at_idx                         | CREATE INDEX mfa_challenge_created_at_idx ON auth.mfa_challenges USING btree (created_at DESC)                                                                                                                                                                                 | 0     |
| unused_low_scan | auth     | mfa_factors                | factor_id_created_at_idx                             | CREATE INDEX factor_id_created_at_idx ON auth.mfa_factors USING btree (user_id, created_at)                                                                                                                                                                                    | 0     |
| unused_low_scan | auth     | mfa_factors                | mfa_factors_last_challenged_at_key                   | CREATE UNIQUE INDEX mfa_factors_last_challenged_at_key ON auth.mfa_factors USING btree (last_challenged_at)                                                                                                                                                                    | 0     |
| unused_low_scan | auth     | mfa_factors                | mfa_factors_user_friendly_name_unique                | CREATE UNIQUE INDEX mfa_factors_user_friendly_name_unique ON auth.mfa_factors USING btree (friendly_name, user_id) WHERE (TRIM(BOTH FROM friendly_name) <> ''::text)                                                                                                           | 0     |
| unused_low_scan | auth     | mfa_factors                | mfa_factors_user_id_idx                              | CREATE INDEX mfa_factors_user_id_idx ON auth.mfa_factors USING btree (user_id)                                                                                                                                                                                                 | 0     |
| unused_low_scan | auth     | oauth_authorizations       | oauth_auth_pending_exp_idx                           | CREATE INDEX oauth_auth_pending_exp_idx ON auth.oauth_authorizations USING btree (expires_at) WHERE (status = 'pending'::auth.oauth_authorization_status)                                                                                                                      | 0     |
| unused_low_scan | auth     | oauth_authorizations       | oauth_authorizations_authorization_code_key          | CREATE UNIQUE INDEX oauth_authorizations_authorization_code_key ON auth.oauth_authorizations USING btree (authorization_code)                                                                                                                                                  | 0     |
| unused_low_scan | auth     | oauth_authorizations       | oauth_authorizations_authorization_id_key            | CREATE UNIQUE INDEX oauth_authorizations_authorization_id_key ON auth.oauth_authorizations USING btree (authorization_id)                                                                                                                                                      | 0     |
| unused_low_scan | auth     | oauth_clients              | oauth_clients_deleted_at_idx                         | CREATE INDEX oauth_clients_deleted_at_idx ON auth.oauth_clients USING btree (deleted_at)                                                                                                                                                                                       | 0     |
| unused_low_scan | auth     | oauth_consents             | oauth_consents_active_client_idx                     | CREATE INDEX oauth_consents_active_client_idx ON auth.oauth_consents USING btree (client_id) WHERE (revoked_at IS NULL)                                                                                                                                                        | 0     |
| unused_low_scan | auth     | oauth_consents             | oauth_consents_active_user_client_idx                | CREATE INDEX oauth_consents_active_user_client_idx ON auth.oauth_consents USING btree (user_id, client_id) WHERE (revoked_at IS NULL)                                                                                                                                          | 0     |
| unused_low_scan | auth     | oauth_consents             | oauth_consents_user_client_unique                    | CREATE UNIQUE INDEX oauth_consents_user_client_unique ON auth.oauth_consents USING btree (user_id, client_id)                                                                                                                                                                  | 0     |
| unused_low_scan | auth     | one_time_tokens            | one_time_tokens_relates_to_hash_idx                  | CREATE INDEX one_time_tokens_relates_to_hash_idx ON auth.one_time_tokens USING hash (relates_to)                                                                                                                                                                               | 0     |
| unused_low_scan | auth     | one_time_tokens            | one_time_tokens_token_hash_hash_idx                  | CREATE INDEX one_time_tokens_token_hash_hash_idx ON auth.one_time_tokens USING hash (token_hash)                                                                                                                                                                               | 0     |
| unused_low_scan | auth     | refresh_tokens             | refresh_tokens_instance_id_idx                       | CREATE INDEX refresh_tokens_instance_id_idx ON auth.refresh_tokens USING btree (instance_id)                                                                                                                                                                                   | 0     |
| unused_low_scan | auth     | refresh_tokens             | refresh_tokens_instance_id_user_id_idx               | CREATE INDEX refresh_tokens_instance_id_user_id_idx ON auth.refresh_tokens USING btree (instance_id, user_id)                                                                                                                                                                  | 0     |
| unused_low_scan | auth     | refresh_tokens             | refresh_tokens_parent_idx                            | CREATE INDEX refresh_tokens_parent_idx ON auth.refresh_tokens USING btree (parent)                                                                                                                                                                                             | 0     |
| unused_low_scan | auth     | refresh_tokens             | refresh_tokens_token_unique                          | CREATE UNIQUE INDEX refresh_tokens_token_unique ON auth.refresh_tokens USING btree (token)                                                                                                                                                                                     | 0     |
| unused_low_scan | auth     | refresh_tokens             | refresh_tokens_updated_at_idx                        | CREATE INDEX refresh_tokens_updated_at_idx ON auth.refresh_tokens USING btree (updated_at DESC)                                                                                                                                                                                | 0     |
| unused_low_scan | auth     | saml_providers             | saml_providers_entity_id_key                         | CREATE UNIQUE INDEX saml_providers_entity_id_key ON auth.saml_providers USING btree (entity_id)                                                                                                                                                                                | 0     |
| unused_low_scan | auth     | saml_providers             | saml_providers_sso_provider_id_idx                   | CREATE INDEX saml_providers_sso_provider_id_idx ON auth.saml_providers USING btree (sso_provider_id)                                                                                                                                                                           | 0     |
| unused_low_scan | auth     | saml_relay_states          | saml_relay_states_created_at_idx                     | CREATE INDEX saml_relay_states_created_at_idx ON auth.saml_relay_states USING btree (created_at DESC)                                                                                                                                                                          | 0     |
| unused_low_scan | auth     | saml_relay_states          | saml_relay_states_for_email_idx                      | CREATE INDEX saml_relay_states_for_email_idx ON auth.saml_relay_states USING btree (for_email)                                                                                                                                                                                 | 0     |
| unused_low_scan | auth     | saml_relay_states          | saml_relay_states_sso_provider_id_idx                | CREATE INDEX saml_relay_states_sso_provider_id_idx ON auth.saml_relay_states USING btree (sso_provider_id)                                                                                                                                                                     | 0     |
| unused_low_scan | auth     | sessions                   | sessions_not_after_idx                               | CREATE INDEX sessions_not_after_idx ON auth.sessions USING btree (not_after DESC)                                                                                                                                                                                              | 0     |
| unused_low_scan | auth     | sessions                   | sessions_oauth_client_id_idx                         | CREATE INDEX sessions_oauth_client_id_idx ON auth.sessions USING btree (oauth_client_id)                                                                                                                                                                                       | 0     |
| unused_low_scan | auth     | sessions                   | user_id_created_at_idx                               | CREATE INDEX user_id_created_at_idx ON auth.sessions USING btree (user_id, created_at)                                                                                                                                                                                         | 0     |
| unused_low_scan | auth     | sso_domains                | sso_domains_domain_idx                               | CREATE UNIQUE INDEX sso_domains_domain_idx ON auth.sso_domains USING btree (lower(domain))                                                                                                                                                                                     | 0     |
| unused_low_scan | auth     | sso_domains                | sso_domains_sso_provider_id_idx                      | CREATE INDEX sso_domains_sso_provider_id_idx ON auth.sso_domains USING btree (sso_provider_id)                                                                                                                                                                                 | 0     |
| unused_low_scan | auth     | sso_providers              | sso_providers_resource_id_idx                        | CREATE UNIQUE INDEX sso_providers_resource_id_idx ON auth.sso_providers USING btree (lower(resource_id))                                                                                                                                                                       | 0     |
| unused_low_scan | auth     | sso_providers              | sso_providers_resource_id_pattern_idx                | CREATE INDEX sso_providers_resource_id_pattern_idx ON auth.sso_providers USING btree (resource_id text_pattern_ops)                                                                                                                                                            | 0     |
| unused_low_scan | auth     | users                      | confirmation_token_idx                               | CREATE UNIQUE INDEX confirmation_token_idx ON auth.users USING btree (confirmation_token) WHERE ((confirmation_token)::text !~ '^[0-9 ]*$'::text)                                                                                                                              | 0     |
| unused_low_scan | auth     | users                      | email_change_token_current_idx                       | CREATE UNIQUE INDEX email_change_token_current_idx ON auth.users USING btree (email_change_token_current) WHERE ((email_change_token_current)::text !~ '^[0-9 ]*$'::text)                                                                                                      | 0     |
| unused_low_scan | auth     | users                      | email_change_token_new_idx                           | CREATE UNIQUE INDEX email_change_token_new_idx ON auth.users USING btree (email_change_token_new) WHERE ((email_change_token_new)::text !~ '^[0-9 ]*$'::text)                                                                                                                  | 0     |
| unused_low_scan | auth     | users                      | reauthentication_token_idx                           | CREATE UNIQUE INDEX reauthentication_token_idx ON auth.users USING btree (reauthentication_token) WHERE ((reauthentication_token)::text !~ '^[0-9 ]*$'::text)                                                                                                                  | 0     |
| unused_low_scan | auth     | users                      | recovery_token_idx                                   | CREATE UNIQUE INDEX recovery_token_idx ON auth.users USING btree (recovery_token) WHERE ((recovery_token)::text !~ '^[0-9 ]*$'::text)                                                                                                                                          | 0     |
| unused_low_scan | auth     | users                      | users_email_partial_key                              | CREATE UNIQUE INDEX users_email_partial_key ON auth.users USING btree (email) WHERE (is_sso_user = false)                                                                                                                                                                      | 0     |
| unused_low_scan | auth     | users                      | users_instance_id_idx                                | CREATE INDEX users_instance_id_idx ON auth.users USING btree (instance_id)                                                                                                                                                                                                     | 0     |
| unused_low_scan | auth     | users                      | users_phone_key                                      | CREATE UNIQUE INDEX users_phone_key ON auth.users USING btree (phone)                                                                                                                                                                                                          | 0     |
| unused_low_scan | public   | conversationparticipants   | idx_conversationparticipants_user_active             | CREATE INDEX idx_conversationparticipants_user_active ON public.conversationparticipants USING btree (user_id) WHERE (is_deleted = false)                                                                                                                                      | 0     |
| unused_low_scan | public   | defaulters_mv              | idx_defaulters_overdue_count                         | CREATE INDEX idx_defaulters_overdue_count ON public.defaulters_mv USING btree (overdue_count DESC)                                                                                                                                                                             | 0     |
| unused_low_scan | public   | deworming                  | idx_deworming_inventory_active                       | CREATE INDEX idx_deworming_inventory_active ON public.deworming USING btree (inventory_id) WHERE (is_deleted = false)                                                                                                                                                          | 0     |
| unused_low_scan | public   | deworming                  | idx_deworming_outside_flag                           | CREATE INDEX idx_deworming_outside_flag ON public.deworming USING btree (outside) WHERE (is_deleted = false)                                                                                                                                                                   | 0     |
| unused_low_scan | public   | deworming                  | idx_deworming_patient_active                         | CREATE INDEX idx_deworming_patient_active ON public.deworming USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                              | 0     |
| unused_low_scan | public   | deworming                  | idx_deworming_vaccine_active                         | CREATE INDEX idx_deworming_vaccine_active ON public.deworming USING btree (vaccine_id) WHERE (is_deleted = false)                                                                                                                                                              | 0     |
| unused_low_scan | public   | deworming                  | idx_deworming_visit_active                           | CREATE INDEX idx_deworming_visit_active ON public.deworming USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                                  | 0     |
| unused_low_scan | public   | deworming                  | idx_deworming_vital_active                           | CREATE INDEX idx_deworming_vital_active ON public.deworming USING btree (vital_id) WHERE (is_deleted = false)                                                                                                                                                                  | 0     |
| unused_low_scan | public   | deworming_history          | deworming_history_deworming_id_version_no_idx        | CREATE INDEX deworming_history_deworming_id_version_no_idx ON public.deworming_history USING btree (deworming_id, version_no DESC)                                                                                                                                             | 0     |
| unused_low_scan | public   | guardians                  | guardians_contact_number_key                         | CREATE UNIQUE INDEX guardians_contact_number_key ON public.guardians USING btree (contact_number)                                                                                                                                                                              | 0     |
| unused_low_scan | public   | guardians                  | guardians_user_id_uniq                               | CREATE UNIQUE INDEX guardians_user_id_uniq ON public.guardians USING btree (user_id) WHERE (COALESCE(is_deleted, false) = false)                                                                                                                                               | 0     |
| unused_low_scan | public   | immunizations              | idx_immunizations_inventory_active                   | CREATE INDEX idx_immunizations_inventory_active ON public.immunizations USING btree (inventory_id) WHERE (is_deleted = false)                                                                                                                                                  | 0     |
| unused_low_scan | public   | immunizations              | idx_immunizations_outside_flag                       | CREATE INDEX idx_immunizations_outside_flag ON public.immunizations USING btree (outside) WHERE (is_deleted = false)                                                                                                                                                           | 0     |
| unused_low_scan | public   | immunizations              | idx_immunizations_visit_active                       | CREATE INDEX idx_immunizations_visit_active ON public.immunizations USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                          | 0     |
| unused_low_scan | public   | immunizations              | idx_immunizations_vital_active                       | CREATE INDEX idx_immunizations_vital_active ON public.immunizations USING btree (vital_id) WHERE (is_deleted = false)                                                                                                                                                          | 0     |
| unused_low_scan | public   | immunizations_history      | idx_immunizations_history_changed_fields             | CREATE INDEX idx_immunizations_history_changed_fields ON public.immunizations_history USING gin (changed_fields)                                                                                                                                                               | 0     |
| unused_low_scan | public   | inventory                  | ux_inventory_identity_active                         | CREATE UNIQUE INDEX ux_inventory_identity_active ON public.inventory USING btree (vaccine_id, lot_number, expiration_date, COALESCE(storage_location, ''::text)) WHERE (is_deleted = false)                                                                                    | 0     |
| unused_low_scan | public   | inventory_requests         | idx_inventory_requests_status                        | CREATE INDEX idx_inventory_requests_status ON public.inventory_requests USING btree (status, requested_at)                                                                                                                                                                     | 0     |
| unused_low_scan | public   | inventory_requests_history | inventory_requests_history_request_id_version_no_idx | CREATE INDEX inventory_requests_history_request_id_version_no_idx ON public.inventory_requests_history USING btree (request_id, version_no DESC)                                                                                                                               | 0     |
| unused_low_scan | public   | messages                   | idx_messages_conversation_created                    | CREATE INDEX idx_messages_conversation_created ON public.messages USING btree (conversation_id, created_at DESC NULLS LAST)                                                                                                                                                    | 0     |
| unused_low_scan | public   | messages                   | idx_messages_conversation_time                       | CREATE INDEX idx_messages_conversation_time ON public.messages USING btree (conversation_id, created_at DESC) WHERE (is_deleted = false)                                                                                                                                       | 0     |
| unused_low_scan | public   | messages                   | idx_messages_conversation_ts                         | CREATE INDEX idx_messages_conversation_ts ON public.messages USING btree (conversation_id, created_at DESC)                                                                                                                                                                    | 0     |
| unused_low_scan | public   | messages                   | idx_messages_conversation_unread                     | CREATE INDEX idx_messages_conversation_unread ON public.messages USING btree (conversation_id) WHERE ((read_at IS NULL) AND (is_deleted = false))                                                                                                                              | 0     |
| unused_low_scan | public   | messages                   | idx_messages_sender_ts                               | CREATE INDEX idx_messages_sender_ts ON public.messages USING btree (sender_id, created_at DESC)                                                                                                                                                                                | 0     |
| unused_low_scan | public   | notifications              | idx_notifications_channel                            | CREATE INDEX idx_notifications_channel ON public.notifications USING btree (channel)                                                                                                                                                                                           | 0     |
| unused_low_scan | public   | notifications              | idx_notifications_created_at                         | CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at)                                                                                                                                                                                     | 0     |
| unused_low_scan | public   | notifications              | idx_notifications_recipient_user_id                  | CREATE INDEX idx_notifications_recipient_user_id ON public.notifications USING btree (recipient_user_id)                                                                                                                                                                       | 0     |
| unused_low_scan | public   | notifications              | idx_notifications_scheduled_at                       | CREATE INDEX idx_notifications_scheduled_at ON public.notifications USING btree (scheduled_at)                                                                                                                                                                                 | 0     |
| unused_low_scan | public   | notifications              | idx_notifications_status                             | CREATE INDEX idx_notifications_status ON public.notifications USING btree (status)                                                                                                                                                                                             | 0     |
| unused_low_scan | public   | notifications              | idx_notifications_status_time                        | CREATE INDEX idx_notifications_status_time ON public.notifications USING btree (status, scheduled_at) WHERE (is_deleted = false)                                                                                                                                               | 0     |
| unused_low_scan | public   | notifications              | idx_notifications_status_ts                          | CREATE INDEX idx_notifications_status_ts ON public.notifications USING btree (status, created_at DESC)                                                                                                                                                                         | 0     |
| unused_low_scan | public   | notifications              | idx_notifications_unread                             | CREATE INDEX idx_notifications_unread ON public.notifications USING btree (recipient_user_id) WHERE ((read_at IS NULL) AND (is_deleted = false))                                                                                                                               | 0     |
| unused_low_scan | public   | patients                   | idx_patients_active_name                             | CREATE INDEX idx_patients_active_name ON public.patients USING btree (firstname, middlename, surname) WHERE (is_deleted = false)                                                                                                                                               | 0     |
| unused_low_scan | public   | patients                   | idx_patients_full_name_trgm                          | CREATE INDEX idx_patients_full_name_trgm ON public.patients USING gin (full_name gin_trgm_ops) WHERE (is_deleted = false)                                                                                                                                                      | 0     |
| unused_low_scan | public   | patients                   | idx_patients_qr_nonce                                | CREATE INDEX idx_patients_qr_nonce ON public.patients USING btree (qr_nonce)                                                                                                                                                                                                   | 0     |
| unused_low_scan | public   | patients_history           | idx_patients_history_changed_fields                  | CREATE INDEX idx_patients_history_changed_fields ON public.patients_history USING gin (changed_fields)                                                                                                                                                                         | 0     |
| unused_low_scan | public   | patientschedule            | idx_patientschedule_overdue                          | CREATE INDEX idx_patientschedule_overdue ON public.patientschedule USING btree (patient_id, scheduled_date) WHERE (((status)::text = ANY ((ARRAY['Scheduled'::character varying, 'Due'::character varying, 'Overdue'::character varying])::text[])) AND (actual_date IS NULL)) | 0     |
| unused_low_scan | public   | patientschedule_history    | idx_ps_history_changed_fields                        | CREATE INDEX idx_ps_history_changed_fields ON public.patientschedule_history USING gin (changed_fields)                                                                                                                                                                        | 0     |
| unused_low_scan | public   | receiving_report_items     | idx_receiving_report_items_inventory_id              | CREATE INDEX idx_receiving_report_items_inventory_id ON public.receiving_report_items USING btree (inventory_id)                                                                                                                                                               | 0     |
| unused_low_scan | public   | receiving_report_items     | idx_receiving_report_items_vaccine_id                | CREATE INDEX idx_receiving_report_items_vaccine_id ON public.receiving_report_items USING btree (vaccine_id)                                                                                                                                                                   | 0     |
| unused_low_scan | public   | receiving_reports          | idx_receiving_reports_status                         | CREATE INDEX idx_receiving_reports_status ON public.receiving_reports USING btree (status)                                                                                                                                                                                     | 0     |
| unused_low_scan | public   | receiving_reports          | receiving_reports_report_number_key                  | CREATE UNIQUE INDEX receiving_reports_report_number_key ON public.receiving_reports USING btree (report_number)                                                                                                                                                                | 0     |
| unused_low_scan | public   | schedule_doses             | schedule_doses_schedule_id_dose_number_key           | CREATE UNIQUE INDEX schedule_doses_schedule_id_dose_number_key ON public.schedule_doses USING btree (schedule_id, dose_number)                                                                                                                                                 | 0     |
| unused_low_scan | public   | schedule_master            | idx_schedule_master_vaccine                          | CREATE INDEX idx_schedule_master_vaccine ON public.schedule_master USING btree (vaccine_id)                                                                                                                                                                                    | 0     |
| unused_low_scan | public   | users                      | idx_users_contact_number                             | CREATE INDEX idx_users_contact_number ON public.users USING btree (contact_number)                                                                                                                                                                                             | 0     |
| unused_low_scan | public   | users                      | idx_users_email_lower                                | CREATE INDEX idx_users_email_lower ON public.users USING btree (lower((email)::text))                                                                                                                                                                                          | 0     |
| unused_low_scan | public   | users                      | idx_users_full_name_trgm                             | CREATE INDEX idx_users_full_name_trgm ON public.users USING gin (full_name gin_trgm_ops) WHERE (is_deleted = false)                                                                                                                                                            | 0     |
| unused_low_scan | public   | users                      | idx_users_role_status                                | CREATE INDEX idx_users_role_status ON public.users USING btree (role, user_status) WHERE (is_deleted = false)                                                                                                                                                                  | 0     |
| unused_low_scan | public   | users                      | idx_users_status                                     | CREATE INDEX idx_users_status ON public.users USING btree (user_status) WHERE (is_deleted = false)                                                                                                                                                                             | 0     |
| unused_low_scan | public   | users                      | idx_users_username_lower                             | CREATE INDEX idx_users_username_lower ON public.users USING btree (lower((username)::text))                                                                                                                                                                                    | 0     |
| unused_low_scan | public   | users_history              | idx_users_history_changed_fields                     | CREATE INDEX idx_users_history_changed_fields ON public.users_history USING gin (changed_fields)                                                                                                                                                                               | 0     |
| unused_low_scan | public   | vaccinemaster              | uq_vaccinemaster_antigen_brand                       | CREATE UNIQUE INDEX uq_vaccinemaster_antigen_brand ON public.vaccinemaster USING btree (antigen_name, brand_name) WHERE (is_deleted = false)                                                                                                                                   | 0     |
| unused_low_scan | public   | vaccinemaster              | uq_vaccinemaster_antigen_brand_active                | CREATE UNIQUE INDEX uq_vaccinemaster_antigen_brand_active ON public.vaccinemaster USING btree (lower((antigen_name)::text), lower((COALESCE(brand_name, ''::character varying))::text)) WHERE (is_deleted = false)                                                             | 0     |
| unused_low_scan | public   | visits                     | idx_visits_patient_active                            | CREATE INDEX idx_visits_patient_active ON public.visits USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                                    | 0     |
| unused_low_scan | public   | vitalsigns                 | idx_vitalsigns_visit_active                          | CREATE INDEX idx_vitalsigns_visit_active ON public.vitalsigns USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                                | 0     |
| unused_low_scan | public   | vitamina                   | idx_vitamina_inventory_active                        | CREATE INDEX idx_vitamina_inventory_active ON public.vitamina USING btree (inventory_id) WHERE (is_deleted = false)                                                                                                                                                            | 0     |
| unused_low_scan | public   | vitamina                   | idx_vitamina_outside_flag                            | CREATE INDEX idx_vitamina_outside_flag ON public.vitamina USING btree (outside) WHERE (is_deleted = false)                                                                                                                                                                     | 0     |
| unused_low_scan | public   | vitamina                   | idx_vitamina_patient_active                          | CREATE INDEX idx_vitamina_patient_active ON public.vitamina USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                                | 0     |
| unused_low_scan | public   | vitamina                   | idx_vitamina_vaccine_active                          | CREATE INDEX idx_vitamina_vaccine_active ON public.vitamina USING btree (vaccine_id) WHERE (is_deleted = false)                                                                                                                                                                | 0     |
| unused_low_scan | public   | vitamina                   | idx_vitamina_visit_active                            | CREATE INDEX idx_vitamina_visit_active ON public.vitamina USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                                    | 0     |
| unused_low_scan | public   | vitamina                   | idx_vitamina_vital_active                            | CREATE INDEX idx_vitamina_vital_active ON public.vitamina USING btree (vital_id) WHERE (is_deleted = false)                                                                                                                                                                    | 0     |
| unused_low_scan | public   | vitamina_history           | vitamina_history_vitamina_id_version_no_idx          | CREATE INDEX vitamina_history_vitamina_id_version_no_idx ON public.vitamina_history USING btree (vitamina_id, version_no DESC)                                                                                                                                                 | 0     |
| unused_low_scan | realtime | messages                   | messages_inserted_at_topic_index                     | CREATE INDEX messages_inserted_at_topic_index ON ONLY realtime.messages USING btree (inserted_at DESC, topic) WHERE ((extension = 'broadcast'::text) AND (private IS TRUE))                                                                                                    | 0     |
| unused_low_scan | realtime | subscription               | ix_realtime_subscription_entity                      | CREATE INDEX ix_realtime_subscription_entity ON realtime.subscription USING btree (entity)                                                                                                                                                                                     | 0     |
| unused_low_scan | storage  | buckets                    | bname                                                | CREATE UNIQUE INDEX bname ON storage.buckets USING btree (name)                                                                                                                                                                                                                | 0     |
| unused_low_scan | storage  | objects                    | bucketid_objname                                     | CREATE UNIQUE INDEX bucketid_objname ON storage.objects USING btree (bucket_id, name)                                                                                                                                                                                          | 0     |
| unused_low_scan | storage  | objects                    | idx_objects_bucket_id_name                           | CREATE INDEX idx_objects_bucket_id_name ON storage.objects USING btree (bucket_id, name COLLATE "C")                                                                                                                                                                           | 0     |
| unused_low_scan | storage  | objects                    | idx_objects_lower_name                               | CREATE INDEX idx_objects_lower_name ON storage.objects USING btree ((path_tokens[level]), lower(name) text_pattern_ops, bucket_id, level)                                                                                                                                      | 0     |
| unused_low_scan | storage  | objects                    | name_prefix_search                                   | CREATE INDEX name_prefix_search ON storage.objects USING btree (name text_pattern_ops)                                                                                                                                                                                         | 0     |
| unused_low_scan | storage  | objects                    | objects_bucket_id_level_idx                          | CREATE UNIQUE INDEX objects_bucket_id_level_idx ON storage.objects USING btree (bucket_id, level, name COLLATE "C")                                                                                                                                                            | 0     |
| unused_low_scan | storage  | prefixes                   | idx_prefixes_lower_name                              | CREATE INDEX idx_prefixes_lower_name ON storage.prefixes USING btree (bucket_id, level, ((string_to_array(name, '/'::text))[level]), lower(name) text_pattern_ops)                                                                                                             | 0     |
| unused_low_scan | storage  | s3_multipart_uploads       | idx_multipart_uploads_list                           | CREATE INDEX idx_multipart_uploads_list ON storage.s3_multipart_uploads USING btree (bucket_id, key, created_at)                                                                                                                                                               | 0     |
| unused_low_scan | vault    | secrets                    | secrets_name_idx                                     | CREATE UNIQUE INDEX secrets_name_idx ON vault.secrets USING btree (name) WHERE (name IS NOT NULL)                                                                                                                                                                              | 0     |