-- Indexes with definitions, uniqueness, method, predicates, sizes, and usage stats
WITH idx AS (
  SELECT
    n.nspname AS schema,
    t.relname AS table_name,
    i.relname AS index_name,
    pg_get_indexdef(ix.indexrelid) AS index_def,
    ix.indisunique AS is_unique,
    ix.indisprimary AS is_primary,
    am.amname AS method,
    pg_relation_size(i.oid) AS index_bytes,
    pg_size_pretty(pg_relation_size(i.oid)) AS index_size_pretty
  FROM pg_index ix
  JOIN pg_class t ON t.oid = ix.indrelid
  JOIN pg_class i ON i.oid = ix.indexrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  JOIN pg_am am ON am.oid = i.relam
  WHERE n.nspname NOT IN ('pg_catalog','information_schema')
    AND n.nspname NOT LIKE 'pg_toast%'
    AND n.nspname NOT LIKE 'pg_temp%'
    AND n.nspname = 'public' -- Limit to public schema only
), usage AS (
  SELECT
    n.nspname AS schema,
    c.relname AS index_name,
    s.idx_scan,
    s.idx_tup_read,
    s.idx_tup_fetch
  FROM pg_stat_user_indexes s
  JOIN pg_class c ON c.oid = s.indexrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
)
SELECT
  idx.schema,
  idx.table_name,
  idx.index_name,
  idx.method,
  idx.is_primary,
  idx.is_unique,
  idx.index_def,
  idx.index_size_pretty,
  COALESCE(usage.idx_scan,0) AS idx_scan,
  COALESCE(usage.idx_tup_read,0) AS idx_tup_read,
  COALESCE(usage.idx_tup_fetch,0) AS idx_tup_fetch
FROM idx
LEFT JOIN usage ON usage.schema = idx.schema AND usage.index_name = idx.index_name
ORDER BY idx.schema, idx.table_name, idx.index_name;

| schema | table_name                    | index_name                                                  | method | is_primary | is_unique | index_def                                                                                                                                                                                                                                                                      | index_size_pretty | idx_scan | idx_tup_read | idx_tup_fetch |
| ------ | ----------------------------- | ----------------------------------------------------------- | ------ | ---------- | --------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ----------------- | -------- | ------------ | ------------- |
| public | activity_action_types         | activity_action_types_pkey                                  | btree  | true       | true      | CREATE UNIQUE INDEX activity_action_types_pkey ON public.activity_action_types USING btree (action_type)                                                                                                                                                                       | 16 kB             | 139      | 936          | 925           |
| public | activitylogs                  | activitylogs_pkey                                           | btree  | true       | true      | CREATE UNIQUE INDEX activitylogs_pkey ON public.activitylogs USING btree (log_id)                                                                                                                                                                                              | 184 kB            | 590      | 125982       | 117856        |
| public | activitylogs                  | idx_activitylogs_action_time                                | btree  | false      | false     | CREATE INDEX idx_activitylogs_action_time ON public.activitylogs USING btree (action_type, "timestamp" DESC)                                                                                                                                                                   | 96 kB             | 119      | 16722        | 3062          |
| public | activitylogs                  | idx_activitylogs_user_login                                 | btree  | false      | false     | CREATE INDEX idx_activitylogs_user_login ON public.activitylogs USING btree (user_id, action_type, "timestamp" DESC)                                                                                                                                                           | 104 kB            | 8849     | 155537       | 33270         |
| public | birthhistory                  | birthhistory_pkey                                           | btree  | true       | true      | CREATE UNIQUE INDEX birthhistory_pkey ON public.birthhistory USING btree (birthhistory_id)                                                                                                                                                                                     | 16 kB             | 83       | 37           | 11            |
| public | birthhistory                  | uq_birthhistory_patient                                     | btree  | false      | true      | CREATE UNIQUE INDEX uq_birthhistory_patient ON public.birthhistory USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                         | 16 kB             | 7153     | 6961         | 6958          |
| public | conversationparticipants      | conversationparticipants_pkey                               | btree  | true       | true      | CREATE UNIQUE INDEX conversationparticipants_pkey ON public.conversationparticipants USING btree (conversation_participant_id)                                                                                                                                                 | 16 kB             | 179      | 676          | 220           |
| public | conversationparticipants      | idx_conversationparticipants_user_active                    | btree  | false      | false     | CREATE INDEX idx_conversationparticipants_user_active ON public.conversationparticipants USING btree (user_id) WHERE (is_deleted = false)                                                                                                                                      | 16 kB             | 0        | 0            | 0             |
| public | conversations                 | conversations_pkey                                          | btree  | true       | true      | CREATE UNIQUE INDEX conversations_pkey ON public.conversations USING btree (conversation_id)                                                                                                                                                                                   | 16 kB             | 908      | 990          | 537           |
| public | defaulters_mv                 | idx_defaulters_overdue_count                                | btree  | false      | false     | CREATE INDEX idx_defaulters_overdue_count ON public.defaulters_mv USING btree (overdue_count DESC)                                                                                                                                                                             | 8192 bytes        | 0        | 0            | 0             |
| public | deworming                     | deworming_pkey                                              | btree  | true       | true      | CREATE UNIQUE INDEX deworming_pkey ON public.deworming USING btree (deworming_id)                                                                                                                                                                                              | 8192 bytes        | 120      | 6            | 6             |
| public | deworming                     | idx_deworming_inventory_active                              | btree  | false      | false     | CREATE INDEX idx_deworming_inventory_active ON public.deworming USING btree (inventory_id) WHERE (is_deleted = false)                                                                                                                                                          | 8192 bytes        | 0        | 0            | 0             |
| public | deworming                     | idx_deworming_outside_flag                                  | btree  | false      | false     | CREATE INDEX idx_deworming_outside_flag ON public.deworming USING btree (outside) WHERE (is_deleted = false)                                                                                                                                                                   | 8192 bytes        | 0        | 0            | 0             |
| public | deworming                     | idx_deworming_patient_active                                | btree  | false      | false     | CREATE INDEX idx_deworming_patient_active ON public.deworming USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                              | 8192 bytes        | 0        | 0            | 0             |
| public | deworming                     | idx_deworming_vaccine_active                                | btree  | false      | false     | CREATE INDEX idx_deworming_vaccine_active ON public.deworming USING btree (vaccine_id) WHERE (is_deleted = false)                                                                                                                                                              | 8192 bytes        | 0        | 0            | 0             |
| public | deworming                     | idx_deworming_visit_active                                  | btree  | false      | false     | CREATE INDEX idx_deworming_visit_active ON public.deworming USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                                  | 8192 bytes        | 0        | 0            | 0             |
| public | deworming                     | idx_deworming_vital_active                                  | btree  | false      | false     | CREATE INDEX idx_deworming_vital_active ON public.deworming USING btree (vital_id) WHERE (is_deleted = false)                                                                                                                                                                  | 8192 bytes        | 0        | 0            | 0             |
| public | deworming_history             | deworming_history_deworming_id_version_no_idx               | btree  | false      | false     | CREATE INDEX deworming_history_deworming_id_version_no_idx ON public.deworming_history USING btree (deworming_id, version_no DESC)                                                                                                                                             | 8192 bytes        | 0        | 0            | 0             |
| public | deworming_history             | deworming_history_pkey                                      | btree  | true       | true      | CREATE UNIQUE INDEX deworming_history_pkey ON public.deworming_history USING btree (history_id)                                                                                                                                                                                | 8192 bytes        | 101      | 0            | 0             |
| public | faqs                          | faqs_pkey                                                   | btree  | true       | true      | CREATE UNIQUE INDEX faqs_pkey ON public.faqs USING btree (faq_id)                                                                                                                                                                                                              | 16 kB             | 32       | 60           | 60            |
| public | guardian_auto_send_settings   | guardian_auto_send_settings_guardian_id_key                 | btree  | false      | true      | CREATE UNIQUE INDEX guardian_auto_send_settings_guardian_id_key ON public.guardian_auto_send_settings USING btree (guardian_id)                                                                                                                                                | 8192 bytes        | 0        | 0            | 0             |
| public | guardian_auto_send_settings   | guardian_auto_send_settings_pkey                            | btree  | true       | true      | CREATE UNIQUE INDEX guardian_auto_send_settings_pkey ON public.guardian_auto_send_settings USING btree (id)                                                                                                                                                                    | 8192 bytes        | 8        | 0            | 0             |
| public | guardian_auto_send_settings   | idx_guardian_auto_send_created_by                           | btree  | false      | false     | CREATE INDEX idx_guardian_auto_send_created_by ON public.guardian_auto_send_settings USING btree (created_by)                                                                                                                                                                  | 8192 bytes        | 154      | 0            | 0             |
| public | guardian_auto_send_settings   | idx_guardian_auto_send_deleted_by                           | btree  | false      | false     | CREATE INDEX idx_guardian_auto_send_deleted_by ON public.guardian_auto_send_settings USING btree (deleted_by)                                                                                                                                                                  | 8192 bytes        | 154      | 0            | 0             |
| public | guardian_auto_send_settings   | idx_guardian_auto_send_enabled                              | btree  | false      | false     | CREATE INDEX idx_guardian_auto_send_enabled ON public.guardian_auto_send_settings USING btree (auto_send_enabled)                                                                                                                                                              | 8192 bytes        | 0        | 0            | 0             |
| public | guardian_auto_send_settings   | idx_guardian_auto_send_guardian_id                          | btree  | false      | false     | CREATE INDEX idx_guardian_auto_send_guardian_id ON public.guardian_auto_send_settings USING btree (guardian_id)                                                                                                                                                                | 8192 bytes        | 44       | 0            | 0             |
| public | guardian_auto_send_settings   | idx_guardian_auto_send_is_deleted                           | btree  | false      | false     | CREATE INDEX idx_guardian_auto_send_is_deleted ON public.guardian_auto_send_settings USING btree (is_deleted)                                                                                                                                                                  | 8192 bytes        | 0        | 0            | 0             |
| public | guardian_auto_send_settings   | idx_guardian_auto_send_updated_by                           | btree  | false      | false     | CREATE INDEX idx_guardian_auto_send_updated_by ON public.guardian_auto_send_settings USING btree (updated_by)                                                                                                                                                                  | 8192 bytes        | 154      | 0            | 0             |
| public | guardians                     | guardians_contact_number_key                                | btree  | false      | true      | CREATE UNIQUE INDEX guardians_contact_number_key ON public.guardians USING btree (contact_number)                                                                                                                                                                              | 16 kB             | 0        | 0            | 0             |
| public | guardians                     | guardians_pkey                                              | btree  | true       | true      | CREATE UNIQUE INDEX guardians_pkey ON public.guardians USING btree (guardian_id)                                                                                                                                                                                               | 16 kB             | 16240    | 16237        | 16189         |
| public | guardians                     | guardians_user_id_uniq                                      | btree  | false      | true      | CREATE UNIQUE INDEX guardians_user_id_uniq ON public.guardians USING btree (user_id) WHERE (COALESCE(is_deleted, false) = false)                                                                                                                                               | 16 kB             | 0        | 0            | 0             |
| public | health_staff_types            | health_staff_types_pkey                                     | btree  | true       | true      | CREATE UNIQUE INDEX health_staff_types_pkey ON public.health_staff_types USING btree (code)                                                                                                                                                                                    | 16 kB             | 104      | 300          | 299           |
| public | immunizations                 | idx_immunizations_inventory_active                          | btree  | false      | false     | CREATE INDEX idx_immunizations_inventory_active ON public.immunizations USING btree (inventory_id) WHERE (is_deleted = false)                                                                                                                                                  | 16 kB             | 0        | 0            | 0             |
| public | immunizations                 | idx_immunizations_outside_flag                              | btree  | false      | false     | CREATE INDEX idx_immunizations_outside_flag ON public.immunizations USING btree (outside) WHERE (is_deleted = false)                                                                                                                                                           | 16 kB             | 0        | 0            | 0             |
| public | immunizations                 | idx_immunizations_patient_active                            | btree  | false      | false     | CREATE INDEX idx_immunizations_patient_active ON public.immunizations USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                      | 16 kB             | 56       | 73           | 13            |
| public | immunizations                 | idx_immunizations_vaccine_active                            | btree  | false      | false     | CREATE INDEX idx_immunizations_vaccine_active ON public.immunizations USING btree (vaccine_id) WHERE (is_deleted = false)                                                                                                                                                      | 16 kB             | 15       | 35           | 0             |
| public | immunizations                 | idx_immunizations_vaccine_dose                              | btree  | false      | false     | CREATE INDEX idx_immunizations_vaccine_dose ON public.immunizations USING btree (vaccine_id, dose_number)                                                                                                                                                                      | 16 kB             | 100      | 484          | 150           |
| public | immunizations                 | idx_immunizations_visit_active                              | btree  | false      | false     | CREATE INDEX idx_immunizations_visit_active ON public.immunizations USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                          | 16 kB             | 0        | 0            | 0             |
| public | immunizations                 | idx_immunizations_visit_vaccine                             | btree  | false      | false     | CREATE INDEX idx_immunizations_visit_vaccine ON public.immunizations USING btree (visit_id, vaccine_id)                                                                                                                                                                        | 16 kB             | 5507     | 7329         | 6420          |
| public | immunizations                 | idx_immunizations_vital_active                              | btree  | false      | false     | CREATE INDEX idx_immunizations_vital_active ON public.immunizations USING btree (vital_id) WHERE (is_deleted = false)                                                                                                                                                          | 16 kB             | 0        | 0            | 0             |
| public | immunizations                 | immunizations_pkey                                          | btree  | true       | true      | CREATE UNIQUE INDEX immunizations_pkey ON public.immunizations USING btree (immunization_id)                                                                                                                                                                                   | 16 kB             | 210      | 3834         | 2437          |
| public | immunizations_history         | idx_immunizations_history_changed_fields                    | gin    | false      | false     | CREATE INDEX idx_immunizations_history_changed_fields ON public.immunizations_history USING gin (changed_fields)                                                                                                                                                               | 16 kB             | 0        | 0            | 0             |
| public | immunizations_history         | idx_immunizations_history_im                                | btree  | false      | false     | CREATE INDEX idx_immunizations_history_im ON public.immunizations_history USING btree (immunization_id, version_no DESC)                                                                                                                                                       | 8192 bytes        | 4        | 3            | 1             |
| public | immunizations_history         | immunizations_history_pkey                                  | btree  | true       | true      | CREATE UNIQUE INDEX immunizations_history_pkey ON public.immunizations_history USING btree (history_id)                                                                                                                                                                        | 8192 bytes        | 206      | 30           | 22            |
| public | inventory                     | idx_inventory_vaccine                                       | btree  | false      | false     | CREATE INDEX idx_inventory_vaccine ON public.inventory USING btree (vaccine_id) WHERE (is_deleted = false)                                                                                                                                                                     | 16 kB             | 34       | 0            | 0             |
| public | inventory                     | idx_inventory_vaccine_expiration                            | btree  | false      | false     | CREATE INDEX idx_inventory_vaccine_expiration ON public.inventory USING btree (vaccine_id, expiration_date)                                                                                                                                                                    | 16 kB             | 14       | 55           | 0             |
| public | inventory                     | idx_inventory_vaccine_lot                                   | btree  | false      | false     | CREATE INDEX idx_inventory_vaccine_lot ON public.inventory USING btree (vaccine_id, lot_number)                                                                                                                                                                                | 16 kB             | 850      | 1060         | 828           |
| public | inventory                     | inventory_pkey                                              | btree  | true       | true      | CREATE UNIQUE INDEX inventory_pkey ON public.inventory USING btree (inventory_id)                                                                                                                                                                                              | 16 kB             | 418      | 1356         | 704           |
| public | inventory                     | ux_inventory_identity_active                                | btree  | false      | true      | CREATE UNIQUE INDEX ux_inventory_identity_active ON public.inventory USING btree (vaccine_id, lot_number, expiration_date, COALESCE(storage_location, ''::text)) WHERE (is_deleted = false)                                                                                    | 16 kB             | 0        | 0            | 0             |
| public | inventory_history             | idx_inventory_history_inv                                   | btree  | false      | false     | CREATE INDEX idx_inventory_history_inv ON public.inventory_history USING btree (inventory_id, version_no DESC)                                                                                                                                                                 | 40 kB             | 828      | 820          | 647           |
| public | inventory_history             | inventory_history_pkey                                      | btree  | true       | true      | CREATE UNIQUE INDEX inventory_history_pkey ON public.inventory_history USING btree (history_id)                                                                                                                                                                                | 40 kB             | 158      | 5541         | 4036          |
| public | inventory_requests            | idx_inventory_requests_status                               | btree  | false      | false     | CREATE INDEX idx_inventory_requests_status ON public.inventory_requests USING btree (status, requested_at)                                                                                                                                                                     | 8192 bytes        | 0        | 0            | 0             |
| public | inventory_requests            | inventory_requests_pkey                                     | btree  | true       | true      | CREATE UNIQUE INDEX inventory_requests_pkey ON public.inventory_requests USING btree (request_id)                                                                                                                                                                              | 8192 bytes        | 176      | 0            | 0             |
| public | inventory_requests_history    | inventory_requests_history_pkey                             | btree  | true       | true      | CREATE UNIQUE INDEX inventory_requests_history_pkey ON public.inventory_requests_history USING btree (history_id)                                                                                                                                                              | 8192 bytes        | 156      | 0            | 0             |
| public | inventory_requests_history    | inventory_requests_history_request_id_version_no_idx        | btree  | false      | false     | CREATE INDEX inventory_requests_history_request_id_version_no_idx ON public.inventory_requests_history USING btree (request_id, version_no DESC)                                                                                                                               | 8192 bytes        | 0        | 0            | 0             |
| public | inventorytransactions         | inventorytransactions_pkey                                  | btree  | true       | true      | CREATE UNIQUE INDEX inventorytransactions_pkey ON public.inventorytransactions USING btree (transaction_id)                                                                                                                                                                    | 16 kB             | 104      | 1342         | 388           |
| public | inventorytransactions_history | inventorytransactions_history_pkey                          | btree  | true       | true      | CREATE UNIQUE INDEX inventorytransactions_history_pkey ON public.inventorytransactions_history USING btree (history_id)                                                                                                                                                        | 64 kB             | 64       | 4200         | 2291          |
| public | inventorytransactions_history | inventorytransactions_history_transaction_id_version_no_idx | btree  | false      | false     | CREATE INDEX inventorytransactions_history_transaction_id_version_no_idx ON public.inventorytransactions_history USING btree (transaction_id, version_no DESC)                                                                                                                 | 56 kB             | 1839     | 2375         | 1802          |
| public | message_receipts              | idx_message_receipts_user_unread                            | btree  | false      | false     | CREATE INDEX idx_message_receipts_user_unread ON public.message_receipts USING btree (user_id, read_at) WHERE (read_at IS NULL)                                                                                                                                                | 16 kB             | 320      | 945          | 945           |
| public | message_receipts              | message_receipts_message_id_user_id_key                     | btree  | false      | true      | CREATE UNIQUE INDEX message_receipts_message_id_user_id_key ON public.message_receipts USING btree (message_id, user_id)                                                                                                                                                       | 16 kB             | 7216     | 27454        | 6800          |
| public | message_receipts              | message_receipts_pkey                                       | btree  | true       | true      | CREATE UNIQUE INDEX message_receipts_pkey ON public.message_receipts USING btree (receipt_id)                                                                                                                                                                                  | 16 kB             | 42       | 585          | 312           |
| public | messages                      | idx_messages_conversation_created                           | btree  | false      | false     | CREATE INDEX idx_messages_conversation_created ON public.messages USING btree (conversation_id, created_at DESC NULLS LAST)                                                                                                                                                    | 16 kB             | 0        | 0            | 0             |
| public | messages                      | idx_messages_conversation_created_at                        | btree  | false      | false     | CREATE INDEX idx_messages_conversation_created_at ON public.messages USING btree (conversation_id, created_at DESC)                                                                                                                                                            | 16 kB             | 9981     | 53899        | 10640         |
| public | messages                      | idx_messages_conversation_time                              | btree  | false      | false     | CREATE INDEX idx_messages_conversation_time ON public.messages USING btree (conversation_id, created_at DESC) WHERE (is_deleted = false)                                                                                                                                       | 16 kB             | 0        | 0            | 0             |
| public | messages                      | idx_messages_conversation_ts                                | btree  | false      | false     | CREATE INDEX idx_messages_conversation_ts ON public.messages USING btree (conversation_id, created_at DESC)                                                                                                                                                                    | 16 kB             | 0        | 0            | 0             |
| public | messages                      | idx_messages_conversation_unread                            | btree  | false      | false     | CREATE INDEX idx_messages_conversation_unread ON public.messages USING btree (conversation_id) WHERE ((read_at IS NULL) AND (is_deleted = false))                                                                                                                              | 16 kB             | 0        | 0            | 0             |
| public | messages                      | idx_messages_sender_created                                 | btree  | false      | false     | CREATE INDEX idx_messages_sender_created ON public.messages USING btree (sender_id, created_at DESC NULLS LAST)                                                                                                                                                                | 16 kB             | 72       | 0            | 0             |
| public | messages                      | idx_messages_sender_ts                                      | btree  | false      | false     | CREATE INDEX idx_messages_sender_ts ON public.messages USING btree (sender_id, created_at DESC)                                                                                                                                                                                | 16 kB             | 0        | 0            | 0             |
| public | messages                      | messages_pkey                                               | btree  | true       | true      | CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (message_id)                                                                                                                                                                                                  | 16 kB             | 3868     | 19225        | 585           |
| public | notifications                 | idx_notifications_channel                                   | btree  | false      | false     | CREATE INDEX idx_notifications_channel ON public.notifications USING btree (channel)                                                                                                                                                                                           | 16 kB             | 1        | 24           | 0             |
| public | notifications                 | idx_notifications_created_at                                | btree  | false      | false     | CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at)                                                                                                                                                                                     | 16 kB             | 0        | 0            | 0             |
| public | notifications                 | idx_notifications_recipient_status_created                  | btree  | false      | false     | CREATE INDEX idx_notifications_recipient_status_created ON public.notifications USING btree (recipient_user_id, status, created_at DESC NULLS LAST)                                                                                                                            | 16 kB             | 52       | 0            | 0             |
| public | notifications                 | idx_notifications_recipient_user_id                         | btree  | false      | false     | CREATE INDEX idx_notifications_recipient_user_id ON public.notifications USING btree (recipient_user_id)                                                                                                                                                                       | 16 kB             | 0        | 0            | 0             |
| public | notifications                 | idx_notifications_scheduled_at                              | btree  | false      | false     | CREATE INDEX idx_notifications_scheduled_at ON public.notifications USING btree (scheduled_at)                                                                                                                                                                                 | 16 kB             | 0        | 0            | 0             |
| public | notifications                 | idx_notifications_status                                    | btree  | false      | false     | CREATE INDEX idx_notifications_status ON public.notifications USING btree (status)                                                                                                                                                                                             | 16 kB             | 0        | 0            | 0             |
| public | notifications                 | idx_notifications_status_time                               | btree  | false      | false     | CREATE INDEX idx_notifications_status_time ON public.notifications USING btree (status, scheduled_at) WHERE (is_deleted = false)                                                                                                                                               | 16 kB             | 0        | 0            | 0             |
| public | notifications                 | idx_notifications_status_ts                                 | btree  | false      | false     | CREATE INDEX idx_notifications_status_ts ON public.notifications USING btree (status, created_at DESC)                                                                                                                                                                         | 16 kB             | 0        | 0            | 0             |
| public | notifications                 | idx_notifications_unread                                    | btree  | false      | false     | CREATE INDEX idx_notifications_unread ON public.notifications USING btree (recipient_user_id) WHERE ((read_at IS NULL) AND (is_deleted = false))                                                                                                                               | 16 kB             | 0        | 0            | 0             |
| public | notifications                 | idx_notifications_user_ts                                   | btree  | false      | false     | CREATE INDEX idx_notifications_user_ts ON public.notifications USING btree (recipient_user_id, created_at DESC)                                                                                                                                                                | 16 kB             | 998      | 0            | 0             |
| public | notifications                 | notifications_pkey                                          | btree  | true       | true      | CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (notification_id)                                                                                                                                                                                   | 16 kB             | 120      | 819          | 75            |
| public | patients                      | idx_patients_active_name                                    | btree  | false      | false     | CREATE INDEX idx_patients_active_name ON public.patients USING btree (firstname, middlename, surname) WHERE (is_deleted = false)                                                                                                                                               | 16 kB             | 0        | 0            | 0             |
| public | patients                      | idx_patients_dob                                            | btree  | false      | false     | CREATE INDEX idx_patients_dob ON public.patients USING btree (date_of_birth)                                                                                                                                                                                                   | 16 kB             | 58       | 195          | 26            |
| public | patients                      | idx_patients_full_name_trgm                                 | gin    | false      | false     | CREATE INDEX idx_patients_full_name_trgm ON public.patients USING gin (full_name gin_trgm_ops) WHERE (is_deleted = false)                                                                                                                                                      | 192 kB            | 0        | 0            | 0             |
| public | patients                      | idx_patients_guardian_active                                | btree  | false      | false     | CREATE INDEX idx_patients_guardian_active ON public.patients USING btree (guardian_id) WHERE (is_deleted = false)                                                                                                                                                              | 16 kB             | 31       | 449          | 3             |
| public | patients                      | idx_patients_qr_nonce                                       | btree  | false      | false     | CREATE INDEX idx_patients_qr_nonce ON public.patients USING btree (qr_nonce)                                                                                                                                                                                                   | 16 kB             | 14       | 131          | 27            |
| public | patients                      | patients_pkey                                               | btree  | true       | true      | CREATE UNIQUE INDEX patients_pkey ON public.patients USING btree (patient_id)                                                                                                                                                                                                  | 16 kB             | 73543    | 327615       | 85140         |
| public | patients_history              | idx_patients_history_changed_fields                         | gin    | false      | false     | CREATE INDEX idx_patients_history_changed_fields ON public.patients_history USING gin (changed_fields)                                                                                                                                                                         | 200 kB            | 0        | 0            | 0             |
| public | patients_history              | idx_patients_history_patient                                | btree  | false      | false     | CREATE INDEX idx_patients_history_patient ON public.patients_history USING btree (patient_id, version_no DESC)                                                                                                                                                                 | 40 kB             | 1128     | 1324         | 1019          |
| public | patients_history              | patients_history_pkey                                       | btree  | true       | true      | CREATE UNIQUE INDEX patients_history_pkey ON public.patients_history USING btree (history_id)                                                                                                                                                                                  | 40 kB             | 145      | 10109        | 8503          |
| public | patientschedule               | idx_patientschedule_overdue                                 | btree  | false      | false     | CREATE INDEX idx_patientschedule_overdue ON public.patientschedule USING btree (patient_id, scheduled_date) WHERE (((status)::text = ANY ((ARRAY['Scheduled'::character varying, 'Due'::character varying, 'Overdue'::character varying])::text[])) AND (actual_date IS NULL)) | 32 kB             | 0        | 0            | 0             |
| public | patientschedule               | idx_patientschedule_patient                                 | btree  | false      | false     | CREATE INDEX idx_patientschedule_patient ON public.patientschedule USING btree (patient_id)                                                                                                                                                                                    | 40 kB             | 9395     | 158692       | 136484        |
| public | patientschedule               | idx_patientschedule_patient_status                          | btree  | false      | false     | CREATE INDEX idx_patientschedule_patient_status ON public.patientschedule USING btree (patient_id, status)                                                                                                                                                                     | 40 kB             | 20684    | 209673       | 9991          |
| public | patientschedule               | idx_patientschedule_status_date                             | btree  | false      | false     | CREATE INDEX idx_patientschedule_status_date ON public.patientschedule USING btree (status, scheduled_date)                                                                                                                                                                    | 40 kB             | 348      | 622          | 586           |
| public | patientschedule               | idx_patientschedule_status_patient                          | btree  | false      | false     | CREATE INDEX idx_patientschedule_status_patient ON public.patientschedule USING btree (status, patient_id)                                                                                                                                                                     | 40 kB             | 1282     | 705          | 696           |
| public | patientschedule               | idx_patientschedule_vaccine_patient                         | btree  | false      | false     | CREATE INDEX idx_patientschedule_vaccine_patient ON public.patientschedule USING btree (vaccine_id, patient_id)                                                                                                                                                                | 48 kB             | 6165     | 32958        | 16085         |
| public | patientschedule               | patientschedule_pkey                                        | btree  | true       | true      | CREATE UNIQUE INDEX patientschedule_pkey ON public.patientschedule USING btree (patient_schedule_id)                                                                                                                                                                           | 40 kB             | 15097    | 52096        | 38586         |
| public | patientschedule               | uq_patientschedule_patient_vax_dose                         | btree  | false      | true      | CREATE UNIQUE INDEX uq_patientschedule_patient_vax_dose ON public.patientschedule USING btree (patient_id, vaccine_id, dose_number)                                                                                                                                            | 72 kB             | 9241     | 22293        | 18244         |
| public | patientschedule               | uq_patientschedule_unique                                   | btree  | false      | true      | CREATE UNIQUE INDEX uq_patientschedule_unique ON public.patientschedule USING btree (patient_id, vaccine_id, dose_number)                                                                                                                                                      | 72 kB             | 565      | 108          | 43            |
| public | patientschedule_history       | idx_patientschedule_history_ps                              | btree  | false      | false     | CREATE INDEX idx_patientschedule_history_ps ON public.patientschedule_history USING btree (patient_schedule_id, version_no DESC)                                                                                                                                               | 168 kB            | 8338     | 10023        | 6666          |
| public | patientschedule_history       | idx_ps_history_changed_fields                               | gin    | false      | false     | CREATE INDEX idx_ps_history_changed_fields ON public.patientschedule_history USING gin (changed_fields)                                                                                                                                                                        | 1032 kB           | 0        | 0            | 0             |
| public | patientschedule_history       | patientschedule_history_pkey                                | btree  | true       | true      | CREATE UNIQUE INDEX patientschedule_history_pkey ON public.patientschedule_history USING btree (history_id)                                                                                                                                                                    | 208 kB            | 185      | 85182        | 68869         |
| public | receiving_report_items        | idx_receiving_report_items_inventory_id                     | btree  | false      | false     | CREATE INDEX idx_receiving_report_items_inventory_id ON public.receiving_report_items USING btree (inventory_id)                                                                                                                                                               | 16 kB             | 119      | 285          | 130           |
| public | receiving_report_items        | idx_receiving_report_items_report_id                        | btree  | false      | false     | CREATE INDEX idx_receiving_report_items_report_id ON public.receiving_report_items USING btree (report_id)                                                                                                                                                                     | 16 kB             | 291      | 786          | 530           |
| public | receiving_report_items        | idx_receiving_report_items_vaccine_id                       | btree  | false      | false     | CREATE INDEX idx_receiving_report_items_vaccine_id ON public.receiving_report_items USING btree (vaccine_id)                                                                                                                                                                   | 16 kB             | 4        | 6            | 4             |
| public | receiving_report_items        | receiving_report_items_pkey                                 | btree  | true       | true      | CREATE UNIQUE INDEX receiving_report_items_pkey ON public.receiving_report_items USING btree (item_id)                                                                                                                                                                         | 16 kB             | 85       | 1064         | 428           |
| public | receiving_reports             | idx_receiving_reports_created_at                            | btree  | false      | false     | CREATE INDEX idx_receiving_reports_created_at ON public.receiving_reports USING btree (created_at)                                                                                                                                                                             | 16 kB             | 74       | 200          | 178           |
| public | receiving_reports             | idx_receiving_reports_report_number                         | btree  | false      | false     | CREATE INDEX idx_receiving_reports_report_number ON public.receiving_reports USING btree (report_number)                                                                                                                                                                       | 16 kB             | 27       | 45           | 22            |
| public | receiving_reports             | idx_receiving_reports_status                                | btree  | false      | false     | CREATE INDEX idx_receiving_reports_status ON public.receiving_reports USING btree (status)                                                                                                                                                                                     | 16 kB             | 0        | 0            | 0             |
| public | receiving_reports             | receiving_reports_pkey                                      | btree  | true       | true      | CREATE UNIQUE INDEX receiving_reports_pkey ON public.receiving_reports USING btree (report_id)                                                                                                                                                                                 | 16 kB             | 228      | 595          | 305           |
| public | receiving_reports             | receiving_reports_report_number_key                         | btree  | false      | true      | CREATE UNIQUE INDEX receiving_reports_report_number_key ON public.receiving_reports USING btree (report_number)                                                                                                                                                                | 16 kB             | 0        | 0            | 0             |
| public | schedule_doses                | idx_schedule_doses_schedule                                 | btree  | false      | false     | CREATE INDEX idx_schedule_doses_schedule ON public.schedule_doses USING btree (schedule_id)                                                                                                                                                                                    | 16 kB             | 4164     | 8894         | 8879          |
| public | schedule_doses                | schedule_doses_pkey                                         | btree  | true       | true      | CREATE UNIQUE INDEX schedule_doses_pkey ON public.schedule_doses USING btree (id)                                                                                                                                                                                              | 16 kB             | 121      | 755          | 655           |
| public | schedule_doses                | schedule_doses_schedule_id_dose_number_key                  | btree  | false      | true      | CREATE UNIQUE INDEX schedule_doses_schedule_id_dose_number_key ON public.schedule_doses USING btree (schedule_id, dose_number)                                                                                                                                                 | 16 kB             | 0        | 0            | 0             |
| public | schedule_doses                | uq_schedule_doses_schedule_dose                             | btree  | false      | true      | CREATE UNIQUE INDEX uq_schedule_doses_schedule_dose ON public.schedule_doses USING btree (schedule_id, dose_number)                                                                                                                                                            | 16 kB             | 22119    | 31317        | 29919         |
| public | schedule_master               | idx_schedule_master_vaccine                                 | btree  | false      | false     | CREATE INDEX idx_schedule_master_vaccine ON public.schedule_master USING btree (vaccine_id)                                                                                                                                                                                    | 16 kB             | 0        | 0            | 0             |
| public | schedule_master               | schedule_master_pkey                                        | btree  | true       | true      | CREATE UNIQUE INDEX schedule_master_pkey ON public.schedule_master USING btree (id)                                                                                                                                                                                            | 16 kB             | 846      | 1360         | 1316          |
| public | schedule_master               | unique_vaccine_schedule                                     | btree  | false      | true      | CREATE UNIQUE INDEX unique_vaccine_schedule ON public.schedule_master USING btree (vaccine_id)                                                                                                                                                                                 | 16 kB             | 18124    | 16741        | 16280         |
| public | schedule_master               | uq_schedule_master_vaccine                                  | btree  | false      | true      | CREATE UNIQUE INDEX uq_schedule_master_vaccine ON public.schedule_master USING btree (vaccine_id)                                                                                                                                                                              | 16 kB             | 7223     | 7182         | 7178          |
| public | sms_logs                      | idx_sms_logs_created_by                                     | btree  | false      | false     | CREATE INDEX idx_sms_logs_created_by ON public.sms_logs USING btree (created_by)                                                                                                                                                                                               | 8192 bytes        | 154      | 0            | 0             |
| public | sms_logs                      | idx_sms_logs_deleted_by                                     | btree  | false      | false     | CREATE INDEX idx_sms_logs_deleted_by ON public.sms_logs USING btree (deleted_by)                                                                                                                                                                                               | 8192 bytes        | 154      | 0            | 0             |
| public | sms_logs                      | idx_sms_logs_guardian_id                                    | btree  | false      | false     | CREATE INDEX idx_sms_logs_guardian_id ON public.sms_logs USING btree (guardian_id)                                                                                                                                                                                             | 8192 bytes        | 42       | 0            | 0             |
| public | sms_logs                      | idx_sms_logs_is_deleted                                     | btree  | false      | false     | CREATE INDEX idx_sms_logs_is_deleted ON public.sms_logs USING btree (is_deleted)                                                                                                                                                                                               | 8192 bytes        | 0        | 0            | 0             |
| public | sms_logs                      | idx_sms_logs_patient_id                                     | btree  | false      | false     | CREATE INDEX idx_sms_logs_patient_id ON public.sms_logs USING btree (patient_id)                                                                                                                                                                                               | 8192 bytes        | 66       | 0            | 0             |
| public | sms_logs                      | idx_sms_logs_phone_number                                   | btree  | false      | false     | CREATE INDEX idx_sms_logs_phone_number ON public.sms_logs USING btree (phone_number)                                                                                                                                                                                           | 8192 bytes        | 0        | 0            | 0             |
| public | sms_logs                      | idx_sms_logs_sent_at                                        | btree  | false      | false     | CREATE INDEX idx_sms_logs_sent_at ON public.sms_logs USING btree (sent_at DESC)                                                                                                                                                                                                | 8192 bytes        | 4        | 0            | 0             |
| public | sms_logs                      | idx_sms_logs_status                                         | btree  | false      | false     | CREATE INDEX idx_sms_logs_status ON public.sms_logs USING btree (status)                                                                                                                                                                                                       | 8192 bytes        | 0        | 0            | 0             |
| public | sms_logs                      | idx_sms_logs_type                                           | btree  | false      | false     | CREATE INDEX idx_sms_logs_type ON public.sms_logs USING btree (type)                                                                                                                                                                                                           | 8192 bytes        | 0        | 0            | 0             |
| public | sms_logs                      | idx_sms_logs_updated_by                                     | btree  | false      | false     | CREATE INDEX idx_sms_logs_updated_by ON public.sms_logs USING btree (updated_by)                                                                                                                                                                                               | 8192 bytes        | 154      | 0            | 0             |
| public | sms_logs                      | sms_logs_pkey                                               | btree  | true       | true      | CREATE UNIQUE INDEX sms_logs_pkey ON public.sms_logs USING btree (id)                                                                                                                                                                                                          | 8192 bytes        | 4        | 0            | 0             |
| public | sms_templates                 | idx_sms_templates_created_by                                | btree  | false      | false     | CREATE INDEX idx_sms_templates_created_by ON public.sms_templates USING btree (created_by)                                                                                                                                                                                     | 16 kB             | 154      | 0            | 0             |
| public | sms_templates                 | idx_sms_templates_deleted_by                                | btree  | false      | false     | CREATE INDEX idx_sms_templates_deleted_by ON public.sms_templates USING btree (deleted_by)                                                                                                                                                                                     | 16 kB             | 154      | 0            | 0             |
| public | sms_templates                 | idx_sms_templates_is_active                                 | btree  | false      | false     | CREATE INDEX idx_sms_templates_is_active ON public.sms_templates USING btree (is_active)                                                                                                                                                                                       | 16 kB             | 0        | 0            | 0             |
| public | sms_templates                 | idx_sms_templates_is_deleted                                | btree  | false      | false     | CREATE INDEX idx_sms_templates_is_deleted ON public.sms_templates USING btree (is_deleted)                                                                                                                                                                                     | 16 kB             | 0        | 0            | 0             |
| public | sms_templates                 | idx_sms_templates_trigger_type                              | btree  | false      | false     | CREATE INDEX idx_sms_templates_trigger_type ON public.sms_templates USING btree (trigger_type)                                                                                                                                                                                 | 16 kB             | 0        | 0            | 0             |
| public | sms_templates                 | idx_sms_templates_updated_by                                | btree  | false      | false     | CREATE INDEX idx_sms_templates_updated_by ON public.sms_templates USING btree (updated_by)                                                                                                                                                                                     | 16 kB             | 154      | 0            | 0             |
| public | sms_templates                 | sms_templates_pkey                                          | btree  | true       | true      | CREATE UNIQUE INDEX sms_templates_pkey ON public.sms_templates USING btree (id)                                                                                                                                                                                                | 16 kB             | 12       | 32           | 32            |
| public | timestamp_normalization_audit | timestamp_normalization_audit_pkey                          | btree  | true       | true      | CREATE UNIQUE INDEX timestamp_normalization_audit_pkey ON public.timestamp_normalization_audit USING btree (table_name)                                                                                                                                                        | 8192 bytes        | 103      | 0            | 0             |
| public | user_mapping                  | user_mapping_pkey                                           | btree  | true       | true      | CREATE UNIQUE INDEX user_mapping_pkey ON public.user_mapping USING btree (uuid)                                                                                                                                                                                                | 16 kB             | 550      | 904          | 860           |
| public | user_mapping                  | user_mapping_user_id_key                                    | btree  | false      | true      | CREATE UNIQUE INDEX user_mapping_user_id_key ON public.user_mapping USING btree (user_id)                                                                                                                                                                                      | 16 kB             | 5907     | 6445         | 6389          |
| public | user_sessions                 | idx_user_sessions_last_activity                             | btree  | false      | false     | CREATE INDEX idx_user_sessions_last_activity ON public.user_sessions USING btree (last_activity DESC)                                                                                                                                                                          | 16 kB             | 0        | 0            | 0             |
| public | user_sessions                 | user_sessions_pkey                                          | btree  | true       | true      | CREATE UNIQUE INDEX user_sessions_pkey ON public.user_sessions USING btree (user_id)                                                                                                                                                                                           | 16 kB             | 8141     | 15985        | 8136          |
| public | users                         | idx_users_contact_number                                    | btree  | false      | false     | CREATE INDEX idx_users_contact_number ON public.users USING btree (contact_number)                                                                                                                                                                                             | 16 kB             | 0        | 0            | 0             |
| public | users                         | idx_users_email_lower                                       | btree  | false      | false     | CREATE INDEX idx_users_email_lower ON public.users USING btree (lower((email)::text))                                                                                                                                                                                          | 16 kB             | 0        | 0            | 0             |
| public | users                         | idx_users_full_name_trgm                                    | gin    | false      | false     | CREATE INDEX idx_users_full_name_trgm ON public.users USING gin (full_name gin_trgm_ops) WHERE (is_deleted = false)                                                                                                                                                            | 64 kB             | 0        | 0            | 0             |
| public | users                         | idx_users_role_hwtype                                       | btree  | false      | false     | CREATE INDEX idx_users_role_hwtype ON public.users USING btree (role, hs_type)                                                                                                                                                                                                 | 16 kB             | 820      | 3782         | 3774          |
| public | users                         | idx_users_role_status                                       | btree  | false      | false     | CREATE INDEX idx_users_role_status ON public.users USING btree (role, user_status) WHERE (is_deleted = false)                                                                                                                                                                  | 16 kB             | 0        | 0            | 0             |
| public | users                         | idx_users_status                                            | btree  | false      | false     | CREATE INDEX idx_users_status ON public.users USING btree (user_status) WHERE (is_deleted = false)                                                                                                                                                                             | 16 kB             | 0        | 0            | 0             |
| public | users                         | idx_users_username_lower                                    | btree  | false      | false     | CREATE INDEX idx_users_username_lower ON public.users USING btree (lower((username)::text))                                                                                                                                                                                    | 16 kB             | 0        | 0            | 0             |
| public | users                         | users_contact_number_key                                    | btree  | false      | true      | CREATE UNIQUE INDEX users_contact_number_key ON public.users USING btree (contact_number)                                                                                                                                                                                      | 16 kB             | 20       | 12           | 0             |
| public | users                         | users_email_key                                             | btree  | false      | true      | CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email)                                                                                                                                                                                                        | 16 kB             | 41       | 20           | 0             |
| public | users                         | users_pkey                                                  | btree  | true       | true      | CREATE UNIQUE INDEX users_pkey ON public.users USING btree (user_id)                                                                                                                                                                                                           | 16 kB             | 14834    | 25294        | 22367         |
| public | users                         | users_username_key                                          | btree  | false      | true      | CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username)                                                                                                                                                                                                  | 16 kB             | 55       | 0            | 0             |
| public | users_history                 | idx_users_history_changed_fields                            | gin    | false      | false     | CREATE INDEX idx_users_history_changed_fields ON public.users_history USING gin (changed_fields)                                                                                                                                                                               | 256 kB            | 0        | 0            | 0             |
| public | users_history                 | idx_users_history_user                                      | btree  | false      | false     | CREATE INDEX idx_users_history_user ON public.users_history USING btree (user_id, version_no DESC)                                                                                                                                                                             | 40 kB             | 989      | 1230         | 787           |
| public | users_history                 | users_history_pkey                                          | btree  | true       | true      | CREATE UNIQUE INDEX users_history_pkey ON public.users_history USING btree (history_id)                                                                                                                                                                                        | 40 kB             | 119      | 8896         | 7689          |
| public | vaccinemaster                 | uniq_vaccinemaster_antigen_brand_mfr                        | btree  | false      | true      | CREATE UNIQUE INDEX uniq_vaccinemaster_antigen_brand_mfr ON public.vaccinemaster USING btree (lower((antigen_name)::text), lower((brand_name)::text), lower((COALESCE(manufacturer, ''::character varying))::text))                                                            | 16 kB             | 11       | 0            | 0             |
| public | vaccinemaster                 | uq_vaccinemaster_antigen_brand                              | btree  | false      | true      | CREATE UNIQUE INDEX uq_vaccinemaster_antigen_brand ON public.vaccinemaster USING btree (antigen_name, brand_name) WHERE (is_deleted = false)                                                                                                                                   | 16 kB             | 0        | 0            | 0             |
| public | vaccinemaster                 | uq_vaccinemaster_antigen_brand_active                       | btree  | false      | true      | CREATE UNIQUE INDEX uq_vaccinemaster_antigen_brand_active ON public.vaccinemaster USING btree (lower((antigen_name)::text), lower((COALESCE(brand_name, ''::character varying))::text)) WHERE (is_deleted = false)                                                             | 16 kB             | 0        | 0            | 0             |
| public | vaccinemaster                 | vaccinemaster_pkey                                          | btree  | true       | true      | CREATE UNIQUE INDEX vaccinemaster_pkey ON public.vaccinemaster USING btree (vaccine_id)                                                                                                                                                                                        | 16 kB             | 31042    | 36946        | 36209         |
| public | visits                        | idx_visits_patient_active                                   | btree  | false      | false     | CREATE INDEX idx_visits_patient_active ON public.visits USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                                    | 16 kB             | 0        | 0            | 0             |
| public | visits                        | visits_pkey                                                 | btree  | true       | true      | CREATE UNIQUE INDEX visits_pkey ON public.visits USING btree (visit_id)                                                                                                                                                                                                        | 16 kB             | 32759    | 129023       | 128526        |
| public | visits_history                | visits_history_pkey                                         | btree  | true       | true      | CREATE UNIQUE INDEX visits_history_pkey ON public.visits_history USING btree (history_id)                                                                                                                                                                                      | 32 kB             | 126      | 1065         | 734           |
| public | visits_history                | visits_history_visit_id_version_no_idx                      | btree  | false      | false     | CREATE INDEX visits_history_visit_id_version_no_idx ON public.visits_history USING btree (visit_id, version_no DESC)                                                                                                                                                           | 16 kB             | 471      | 576          | 350           |
| public | vitalsigns                    | idx_vitalsigns_visit_active                                 | btree  | false      | false     | CREATE INDEX idx_vitalsigns_visit_active ON public.vitalsigns USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                                | 16 kB             | 0        | 0            | 0             |
| public | vitalsigns                    | vitalsigns_pkey                                             | btree  | true       | true      | CREATE UNIQUE INDEX vitalsigns_pkey ON public.vitalsigns USING btree (vital_id)                                                                                                                                                                                                | 16 kB             | 107      | 117          | 76            |
| public | vitamina                      | idx_vitamina_inventory_active                               | btree  | false      | false     | CREATE INDEX idx_vitamina_inventory_active ON public.vitamina USING btree (inventory_id) WHERE (is_deleted = false)                                                                                                                                                            | 8192 bytes        | 0        | 0            | 0             |
| public | vitamina                      | idx_vitamina_outside_flag                                   | btree  | false      | false     | CREATE INDEX idx_vitamina_outside_flag ON public.vitamina USING btree (outside) WHERE (is_deleted = false)                                                                                                                                                                     | 8192 bytes        | 0        | 0            | 0             |
| public | vitamina                      | idx_vitamina_patient_active                                 | btree  | false      | false     | CREATE INDEX idx_vitamina_patient_active ON public.vitamina USING btree (patient_id) WHERE (is_deleted = false)                                                                                                                                                                | 8192 bytes        | 0        | 0            | 0             |
| public | vitamina                      | idx_vitamina_vaccine_active                                 | btree  | false      | false     | CREATE INDEX idx_vitamina_vaccine_active ON public.vitamina USING btree (vaccine_id) WHERE (is_deleted = false)                                                                                                                                                                | 8192 bytes        | 0        | 0            | 0             |
| public | vitamina                      | idx_vitamina_visit_active                                   | btree  | false      | false     | CREATE INDEX idx_vitamina_visit_active ON public.vitamina USING btree (visit_id) WHERE (is_deleted = false)                                                                                                                                                                    | 8192 bytes        | 0        | 0            | 0             |
| public | vitamina                      | idx_vitamina_vital_active                                   | btree  | false      | false     | CREATE INDEX idx_vitamina_vital_active ON public.vitamina USING btree (vital_id) WHERE (is_deleted = false)                                                                                                                                                                    | 8192 bytes        | 0        | 0            | 0             |
| public | vitamina                      | vitamina_pkey                                               | btree  | true       | true      | CREATE UNIQUE INDEX vitamina_pkey ON public.vitamina USING btree (vitamina_id)                                                                                                                                                                                                 | 8192 bytes        | 71       | 3            | 3             |
| public | vitamina_history              | vitamina_history_pkey                                       | btree  | true       | true      | CREATE UNIQUE INDEX vitamina_history_pkey ON public.vitamina_history USING btree (history_id)                                                                                                                                                                                  | 8192 bytes        | 39       | 0            | 0             |
| public | vitamina_history              | vitamina_history_vitamina_id_version_no_idx                 | btree  | false      | false     | CREATE INDEX vitamina_history_vitamina_id_version_no_idx ON public.vitamina_history USING btree (vitamina_id, version_no DESC)                                                                                                                                                 | 8192 bytes        | 0        | 0            | 0             |